#!/usr/bin/env python3
"""
Fabric Task Flows — Deploy Script (Python)
Generated by @fabric-engineer

Project:   Agent Assist Telco
Task Flow: lambda
Generated: 2026-03-07

Self-contained — no external dependencies beyond Python 3.10+ and ms-fabric-cli.
Can be zipped and distributed independently.

Usage:
    python deploy-agent-assist-telco.py
    python deploy-agent-assist-telco.py --spn-auth
    python deploy-agent-assist-telco.py --workspace my-ws --capacity my-cap
"""

import argparse
import os
import subprocess
import sys
import time
from dataclasses import dataclass, field


# =============================================================================
# Fabric Deploy Utility (embedded — no external imports needed)
# =============================================================================

def run_fab(command: str, capture: bool = False, allow_failure: bool = False) -> str | None:
    """Run a fab CLI command in command-line mode (fab -c 'command').

    Args:
        command: The fab command to run (without the 'fab' prefix).
        capture: If True, capture and return stdout.
        allow_failure: If True, don't raise on non-zero exit or stderr.

    Returns:
        Captured stdout (last line) if capture=True, else None.

    Raises:
        RuntimeError: If command fails and allow_failure is False.
    """
    result = subprocess.run(
        ["fab", "-c", command],
        capture_output=True,
        text=True,
    )

    if not allow_failure and (result.returncode != 0 or result.stderr):
        raise RuntimeError(
            f"fab command failed: {command}\n"
            f"  exit_code: {result.returncode}\n"
            f"  stderr: {result.stderr.strip()}"
        )

    if capture:
        output = result.stdout.strip()
        return output.split("\n")[-1] if output else ""

    return None


def check_auth() -> bool:
    """Check if fab is authenticated by parsing status output text."""
    result = subprocess.run(
        ["fab", "-c", "auth status"],
        capture_output=True,
        text=True,
    )
    return "Not logged in" not in result.stdout


def authenticate_interactive():
    """Authenticate via interactive browser login (command-line mode)."""
    print("  ── Opening Fabric login (browser)...")
    subprocess.run(["fab", "-c", "auth login"], text=True)
    if not check_auth():
        raise RuntimeError("Authentication failed. Run 'fab -c \"auth login\"' manually.")
    print("  ── ✅ Authenticated")


def authenticate_spn(client_id: str = None, client_secret: str = None, tenant_id: str = None):
    """Authenticate via Service Principal (for CI/CD)."""
    client_id = client_id or os.getenv("FABRIC_CLIENT_ID")
    client_secret = client_secret or os.getenv("FABRIC_CLIENT_SECRET")
    tenant_id = tenant_id or os.getenv("FABRIC_TENANT_ID")

    if not all([client_id, client_secret, tenant_id]):
        raise RuntimeError(
            "SPN auth requires FABRIC_CLIENT_ID, FABRIC_CLIENT_SECRET, FABRIC_TENANT_ID"
        )

    print("  ── Authenticating with Service Principal...")
    run_fab(f"auth login -u {client_id} -p {client_secret} --tenant {tenant_id}")
    print("  ── ✅ Authenticated (SPN)")


def fab_exists(path: str) -> bool:
    """Check if a Fabric item exists (idempotency check)."""
    result = subprocess.run(
        ["fab", "-c", f"exists {path}"],
        capture_output=True,
        text=True,
    )
    return "does not exist" not in result.stdout.lower() and result.returncode == 0


@dataclass
class DeployResult:
    label: str
    status: str  # "created", "exists", "failed", "manual"


@dataclass
class FabricDeployer:
    """Manages Fabric workspace deployment with idempotency and retry."""

    workspace: str
    capacity: str = ""
    results: list[DeployResult] = field(default_factory=list)

    def authenticate(self, spn: bool = False):
        """Check auth status; auto-login if needed."""
        print("  Checking authentication...")
        if check_auth():
            print("  ── ✅ Already authenticated")
        elif spn:
            authenticate_spn()
        else:
            authenticate_interactive()

    def create_workspace(self) -> str:
        """Create workspace and assign capacity. Returns workspace ID."""
        ws_path = f"/{self.workspace}.Workspace"
        print(f"\n  Creating workspace: {self.workspace}")

        if fab_exists(ws_path):
            print(f"  ── ✅ Workspace already exists")
        else:
            cmd = f"mkdir {ws_path}"
            if self.capacity:
                cmd += f" -P capacityName={self.capacity}"
            run_fab(cmd, allow_failure=True)
            print(f"  ── ✅ Workspace created")

        # Get workspace ID
        ws_id = run_fab(f"get {ws_path} -q id", capture=True, allow_failure=True) or "(unavailable)"
        print(f"  ── Workspace ID: {ws_id}")
        return ws_id

    def create_item(self, name: str, item_type: str, tree_char: str = "├──",
                    max_retries: int = 3, **params) -> str | None:
        """Create a Fabric item with idempotency and retry.

        Args:
            name: Item display name.
            item_type: Fabric item type (e.g., 'Lakehouse', 'Warehouse').
            tree_char: Tree connector for display.
            max_retries: Number of retry attempts.
            **params: Additional -P parameters (e.g., enableSchemas="true").

        Returns:
            Item ID if created/exists, None if failed.
        """
        path = f"/{self.workspace}.Workspace/{name}.{item_type}"
        label = f"{item_type}: {name}"

        # Idempotency check
        if fab_exists(path):
            print(f"  {tree_char} ✅ {label} (already exists)")
            self.results.append(DeployResult(label, "exists"))
            item_id = run_fab(f"get {path} -q id", capture=True, allow_failure=True)
            return item_id

        # Build command with parameters
        param_str = ""
        if params:
            param_str = " -P " + ",".join(f"{k}={v}" for k, v in params.items())

        # Retry with backoff
        last_error = ""
        for attempt in range(1, max_retries + 1):
            try:
                run_fab(f"mkdir {path}{param_str}")
                print(f"  {tree_char} ✅ {label}")
                self.results.append(DeployResult(label, "created"))
                item_id = run_fab(f"get {path} -q id", capture=True, allow_failure=True)
                return item_id
            except RuntimeError as e:
                last_error = str(e)
                if attempt < max_retries:
                    wait = attempt * 10
                    print(f"  {tree_char} ⚠️  {label} (attempt {attempt} failed, retrying in {wait}s...)")
                    print(f"         Error: {last_error}")
                    import time
                    time.sleep(wait)

        print(f"  {tree_char} ❌ {label} (failed after {max_retries} attempts)")
        print(f"         Error: {last_error}")
        self.results.append(DeployResult(label, "failed"))
        return None

    def manual_step(self, label: str, tree_char: str = "├──"):
        """Record a manual (portal-only) step."""
        print(f"  {tree_char} ⏭️  [MANUAL] {label}")
        self.results.append(DeployResult(label, "manual"))

    def print_summary(self):
        """Print deployment summary."""
        created = sum(1 for r in self.results if r.status == "created")
        exists = sum(1 for r in self.results if r.status == "exists")
        failed = sum(1 for r in self.results if r.status == "failed")
        manual = sum(1 for r in self.results if r.status == "manual")

        print("\n┌──────────────────────────────────────────────────────────────────┐")
        print("│  DEPLOYMENT SUMMARY                                              │")
        print("└──────────────────────────────────────────────────────────────────┘\n")

        icons = {"created": "✅ Created", "exists": "✅ Exists ", "failed": "❌ Failed ",
                 "manual": "⏭️  Manual "}
        for r in self.results:
            print(f"  {icons.get(r.status, '?')}  {r.label}")

        print(f"\n  Created: {created}  |  Already existed: {exists}  |  Failed: {failed}  |  Manual: {manual}")

        if failed > 0:
            print("\n  ⚠️  Some items failed — check errors above and retry.")
            sys.exit(1)

    def print_metadata(self):
        """Print post-deployment metadata (workspace ID, tenant, portal URL)."""
        print("\n┌──────────────────────────────────────────────────────────────────┐")
        print("│  POST-DEPLOYMENT METADATA                                       │")
        print("└──────────────────────────────────────────────────────────────────┘\n")

        ws_id = run_fab(f"get /{self.workspace}.Workspace -q id", capture=True, allow_failure=True) or "(unavailable)"
        print(f"  Workspace ID:   {ws_id}")

        auth_out = run_fab("auth status", capture=True, allow_failure=True) or ""
        print(f"  Workspace URL:  https://app.fabric.microsoft.com/groups/{ws_id}")

        print("\n  Item Details:")
        for r in self.results:
            if r.status in ("created", "exists"):
                item_label = r.label.split(": ", 1)[-1] if ": " in r.label else r.label
                item_type = r.label.split(": ", 1)[0] if ": " in r.label else "Unknown"
                print(f"  ├── {r.label}")

        print("\n  ℹ️  Save these IDs — they are required for CI/CD parameterization")
        print("     and fabric-cicd library configuration.")


def print_banner(project: str, task_flow: str, mode: str = "Deploy to Fabric"):
    """Print the Fabric Task Flows banner."""
    print("""
╔══════════════════════════════════════════════════════════════════╗
║                                                                  ║
║        /@@@@@@@@@@@@/  ┌──────────────────────────────────────┐  ║
║       /@@@@@@@@@@@@/   │ F A B R I C   T A S K   F L O W S    │  ║
║      /@@@@@@@@@/       │ ──────────────────────────────────── │  ║
║     /@@@@@@/           │ Deploy Microsoft Fabric              │  ║
║    /@@@@@@/            │ architectures to production          │  ║
║                        └──────────────────────────────────────┘  ║
║                                                                  ║""")
    print(f"║  Project:   {project:<52} ║")
    print(f"║  Task Flow: {task_flow:<52} ║")
    print(f"║  Mode:      {mode:<52} ║")
    print("""║                                                                  ║
╚══════════════════════════════════════════════════════════════════╝
""")


def prompt_value(env_var: str, prompt_text: str, default: str = "", optional: bool = False) -> str:
    """Prompt for a value with env var fallback."""
    env_val = os.getenv(env_var)
    if env_val:
        return env_val

    if default:
        response = input(f"  ? {prompt_text} (Enter = {default}, or type to rename): ").strip()
        return response or default
    elif optional:
        response = input(f"  ? {prompt_text} (optional, Enter to skip): ").strip()
        return response
    else:
        return input(f"  ? {prompt_text}: ").strip()



# =============================================================================
# Deploy: Agent Assist Telco
# =============================================================================

def main():
    parser = argparse.ArgumentParser(
        description="Deploy Agent Assist Telco (lambda architecture) to Microsoft Fabric"
    )
    parser.add_argument("--workspace", default=os.getenv("FABRIC_WORKSPACE_NAME", "agent-assist-telco-dev"))
    parser.add_argument("--capacity", default=os.getenv("FABRIC_CAPACITY", ""))
    parser.add_argument("--spn-auth", action="store_true", default=False)
    parser.add_argument("--yes", "-y", action="store_true", help="Skip confirmation prompt")
    args = parser.parse_args()

    print_banner("Agent Assist Telco", "lambda")

    # ── Configuration ──────────────────────────────────────────────
    if not args.workspace:
        args.workspace = prompt_value("FABRIC_WORKSPACE_NAME", "Workspace name", "agent-assist-telco-dev")
    if not args.capacity:
        args.capacity = prompt_value("FABRIC_CAPACITY", "Fabric capacity name")

    source_connection_string = prompt_value("SOURCE_CONNECTION_STRING", "Source database connection string (e.g., SQL Server, PostgreSQL — used by Copy Job)", optional=True)
    if not source_connection_string:
        print("  ⚠️  No Connection to source database — related items will be created but not configured")
    event_hub_namespace = prompt_value("EVENT_HUB_NAMESPACE", "Event Hub namespace (Azure Event Hubs that streams events into Fabric)", optional=True)
    if not event_hub_namespace:
        print("  ⚠️  No Azure Event Hub namespace for streaming — related items will be created but not configured")
    event_hub_consumer_group = prompt_value("EVENT_HUB_CONSUMER_GROUP", "Event Hub consumer group (isolates this pipeline's read position — use $Default if unsure)")

    # ── Deployment Plan ─────────────────────────────────────────────
    print("┌──────────────────────────────────────────────────────────────────┐")
    print("│  DEPLOYMENT PLAN                                                 │")
    print("│  {:<66}│".format("  Task flow: lambda  |  Items: 16  |  Waves: 7"))
    print("└──────────────────────────────────────────────────────────────────┘")
    print()
    print("  Wave 1 — Foundation + Compute")
    print("  ├── ☐ Lakehouse: call-transcripts-lakehouse")
    print("  ├── ☐ Warehouse: call-analytics-warehouse")
    print("  ├── ☐ Eventhouse: call-events-eventhouse")
    print("  └── ☐ Environment: spark-env")
    print()
    print("  Wave 2 — Ingestion")
    print("  ├── ☐ Eventstream: call-stream-eventstream")
    print("  └── ☐ Data Pipeline: crm-sync-pipeline")
    print()
    print("  Wave 3 — Processing")
    print("  ├── ☐ Notebook: transcript-etl-notebook")
    print("  └── ☐ KQL Queryset: call-insights-kql")
    print()
    print("  Wave 4 — Serving")
    print("  ├── ☐ Semantic Model: call-analytics-model")
    print("  └── ☐ [MANUAL] Real-Time Dashboard: call-ops-rt-dash")
    print()
    print("  Wave 5 — Visualization")
    print("  ├── ☐ Report: call-analytics-report")
    print("  └── ☐ [MANUAL] Activator: call-alert-activator")
    print()
    print("  Wave 6 — ML")
    print("  ├── ☐ ML Experiment: transcript-ml-experiment")
    print("  ├── ☐ ML Model: transcript-ml-model")
    print("  └── ☐ Notebook: ml-scoring-notebook")
    print()

    if not args.yes:
        confirm = input("  ? Proceed with deployment? [Y/n]: ").strip() or "Y"
        if confirm.upper() != "Y":
            print("  Deployment cancelled.")
            return

    # ── Authenticate ────────────────────────────────────────────────
    deployer = FabricDeployer(workspace=args.workspace, capacity=args.capacity)
    deployer.authenticate(spn=args.spn_auth)

    # ── Workspace ────────────────────────────────────────────────────
    workspace_id = deployer.create_workspace()

    # ── Wave 1 — Foundation + Compute ──────────────────────────────────────
    print("\n  Wave 1 — Foundation + Compute")
    call_transcripts_lakehouse_id = deployer.create_item("call-transcripts-lakehouse", "Lakehouse", "├──", enableSchemas="true")
    call_analytics_warehouse_id = deployer.create_item("call-analytics-warehouse", "Warehouse", "├──")
    call_events_eventhouse_id = deployer.create_item("call-events-eventhouse", "Eventhouse", "├──")
    eh_id = call_events_eventhouse_id or ""
    spark_env_id = deployer.create_item("spark-env", "Environment", "└──")

    # ── Wave 2 — Ingestion ──────────────────────────────────────
    print("\n  Wave 2 — Ingestion")
    call_stream_eventstream_id = deployer.create_item("call-stream-eventstream", "Eventstream", "├──")
    crm_sync_pipeline_id = deployer.create_item("crm-sync-pipeline", "DataPipeline", "└──")

    # ── Wave 3 — Processing ──────────────────────────────────────
    print("\n  Wave 3 — Processing")
    transcript_etl_notebook_id = deployer.create_item("transcript-etl-notebook", "Notebook", "├──")
    call_insights_kql_id = deployer.create_item("call-insights-kql", "KQLQueryset", "└──")

    # ── Wave 4 — Serving ──────────────────────────────────────
    print("\n  Wave 4 — Serving")
    call_analytics_model_id = deployer.create_item("call-analytics-model", "SemanticModel", "├──")
    sm_id = call_analytics_model_id or ""
    deployer.manual_step("Real-Time Dashboard: call-ops-rt-dash", "└──")

    # ── Wave 5 — Visualization ──────────────────────────────────────
    print("\n  Wave 5 — Visualization")
    call_analytics_report_id = deployer.create_item("call-analytics-report", "Report", "├──", semanticModelId=sm_id)
    deployer.manual_step("Activator: call-alert-activator", "└──")

    # ── Wave 6 — ML ──────────────────────────────────────
    print("\n  Wave 6 — ML")
    transcript_ml_experiment_id = deployer.create_item("transcript-ml-experiment", "MLExperiment", "├──")
    transcript_ml_model_id = deployer.create_item("transcript-ml-model", "MLModel", "├──")
    ml_scoring_notebook_id = deployer.create_item("ml-scoring-notebook", "Notebook", "└──")

    # ── Summary ──────────────────────────────────────────────────────
    deployer.print_summary()
    deployer.print_metadata()


if __name__ == "__main__":
    main()
