#!/usr/bin/env bash
# =============================================================================
# Fabric Task Flows — Deploy Script
# Generated by @fabric-engineer
#
# Project:   Agent Assist Telco
# Task Flow: lambda
# Generated: 2026-03-07
# =============================================================================
set -euo pipefail

# ---------------------------------------------------------------------------
# Brand Banner
# ---------------------------------------------------------------------------
print_banner() {
  local project_name="${1:-Project}"
  local task_flow="${2:-unknown}"
  local mode="${3:-Deploy}"

  echo ""
  echo "╔══════════════════════════════════════════════════════════════════╗"
  echo "║                                                                  ║"
  echo "║        /@@@@@@@@@@@@/  ┌──────────────────────────────────────┐  ║"
  echo "║       /@@@@@@@@@@@@/   │ F A B R I C   T A S K   F L O W S    │  ║"
  echo "║      /@@@@@@@@@/       │ ──────────────────────────────────── │  ║"
  echo "║     /@@@@@@/           │ Deploy Microsoft Fabric              │  ║"
  echo "║    /@@@@@@/            │ architectures to production          │  ║"
  echo "║                        └──────────────────────────────────────┘  ║"
  echo "║                                                                  ║"
  printf "║  Project:   %-52s ║\n" "$project_name"
  printf "║  Task Flow: %-52s ║\n" "$task_flow"
  printf "║  Mode:      %-52s ║\n" "$mode"
  echo "║                                                                  ║"
  echo "╚══════════════════════════════════════════════════════════════════╝"
  echo ""
}

# ---------------------------------------------------------------------------
# Configuration
# ---------------------------------------------------------------------------
PROJECT_NAME="Agent Assist Telco"
TASK_FLOW="lambda"

# ---------------------------------------------------------------------------
# Interactive prompts (with env var fallbacks)
# ---------------------------------------------------------------------------
prompt_value() {
  local var_name="$1"
  local prompt_text="$2"
  local default_value="${3:-}"
  local optional="${4:-}"
  local env_value="${!var_name:-}"

  if [[ -n "$env_value" ]]; then
    echo "$env_value"
    return
  fi

  if [[ -n "$default_value" ]]; then
    read -rp "  ? $prompt_text (Enter = $default_value, or type to rename): " input
    echo "${input:-$default_value}"
  elif [[ "$optional" == "optional" ]]; then
    read -rp "  ? $prompt_text (optional, Enter to skip): " input
    echo "$input"
  else
    read -rp "  ? $prompt_text: " input
    echo "$input"
  fi
}

DEPLOY_CREATED=0
DEPLOY_EXISTS=0
DEPLOY_FAILED=0
DEPLOY_LOG=""

fab_mkdir() {
  local path="$1"
  local label="$2"
  local tree_char="${3:-├──}"
  shift 3 2>/dev/null || true
  local extra_args=("$@")
  local max_retries=3
  local err_output

  if fab exists "$path" 2>/dev/null; then
    echo "  $tree_char ✅ $label (already exists)"
    DEPLOY_EXISTS=$((DEPLOY_EXISTS + 1))
    DEPLOY_LOG="${DEPLOY_LOG}\n  ✅ Exists   $label"
    return
  fi

  for attempt in $(seq 1 $max_retries); do
    err_output=$(fab mkdir "$path" "${extra_args[@]}" 2>&1)
    if [ $? -eq 0 ]; then
      echo "  $tree_char ✅ $label"
      DEPLOY_CREATED=$((DEPLOY_CREATED + 1))
      DEPLOY_LOG="${DEPLOY_LOG}\n  ✅ Created  $label"
      return
    fi
    if [ "$attempt" -lt "$max_retries" ]; then
      local wait=$((attempt * 10))
      echo "  $tree_char ⚠️  $label (attempt $attempt failed, retrying in ${wait}s...)"
      echo "         Error: $err_output"
      sleep "$wait"
    fi
  done

  echo "  $tree_char ❌ $label (failed after $max_retries attempts)"
  echo "         Error: $err_output"
  DEPLOY_FAILED=$((DEPLOY_FAILED + 1))
  DEPLOY_LOG="${DEPLOY_LOG}\n  ❌ Failed   $label"
  exit 1
}

# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------
main() {
  print_banner "$PROJECT_NAME" "$TASK_FLOW" "Deploy to Fabric"

  # Preflight: CLI only
  echo "  Checking prerequisites..."
  if ! command -v fab &> /dev/null; then
    echo "  ❌ Fabric CLI (fab) not found."
    echo "     Install with: pip install ms-fabric-cli"
    exit 1
  fi
  echo "  ── ✅ Fabric CLI found"
  echo ""

  echo "┌──────────────────────────────────────────────────────────────────┐"
  echo "│  CONFIGURATION                                                   │"
  echo "│  Fill in the values below or set as environment variables.       │"
  echo "└──────────────────────────────────────────────────────────────────┘"
  echo ""

  FABRIC_WORKSPACE_NAME=$(prompt_value "FABRIC_WORKSPACE_NAME" "Workspace name" "agent-assist-telco-dev")
  FABRIC_CAPACITY_ID=$(prompt_value "FABRIC_CAPACITY_ID" "Fabric capacity ID (GUID from portal → Capacities)")

  # Task-flow-specific prompts
  EVENT_HUB_NAMESPACE=$(prompt_value "EVENT_HUB_NAMESPACE" "Event Hub namespace (for telephony transcription stream)")
  if [[ -z "$EVENT_HUB_NAMESPACE" ]]; then
    echo "  ⚠️  No Event Hub namespace — Eventstream will be created but cannot ingest data"
  fi
  DATAVERSE_ENV=$(prompt_value "DATAVERSE_ENV" "Dataverse environment URL (for CRM sync)")
  if [[ -z "$DATAVERSE_ENV" ]]; then
    echo "  ⚠️  No Dataverse URL — Pipeline will be created but CRM sync won't function"
  fi

  echo ""
  echo "┌──────────────────────────────────────────────────────────────────┐"
  echo "│  DEPLOYMENT PLAN                                                 │"
  printf "│%-66s│\n" "  Task flow: lambda  |  Items: 15  |  Waves: 6"
  echo "└──────────────────────────────────────────────────────────────────┘"
  echo ""
  echo "  Wave 1 ─ Foundation + Compute"
  echo "  ├── ☐ Lakehouse:   call-transcripts-lakehouse"
  echo "  ├── ☐ Warehouse:   call-analytics-warehouse"
  echo "  ├── ☐ Eventhouse:  call-events-eventhouse"
  echo "  └── ☐ Environment: spark-env"
  echo ""
  echo "  Wave 2 ─ Ingestion"
  echo "  ├── ☐ Eventstream: call-stream-eventstream"
  echo "  └── ☐ Pipeline:    crm-sync-pipeline"
  echo ""
  echo "  Wave 3 ─ Processing"
  echo "  ├── ☐ Notebook:    transcript-etl-notebook"
  echo "  └── ☐ KQL Queryset: call-insights-kql"
  echo ""
  echo "  Wave 4 ─ Serving"
  echo "  ├── ☐ Semantic Model: call-analytics-model"
  echo "  └── ☐ RT Dashboard:  call-ops-rt-dash (portal)"
  echo ""
  echo "  Wave 5 ─ Visualization"
  echo "  ├── ☐ Report:    call-analytics-report"
  echo "  └── ☐ Activator: call-alert-activator (portal)"
  echo ""
  echo "  Wave 6 ─ ML"
  echo "  ├── ☐ Experiment: transcript-ml-experiment"
  echo "  ├── ☐ ML Model:   transcript-ml-model"
  echo "  └── ☐ Notebook:   ml-scoring-notebook"
  echo ""

  read -rp "  ? Proceed with deployment? [Y/n]: " confirm
  confirm="${confirm:-Y}"
  if [[ ! "$confirm" =~ ^[Yy] ]]; then
    echo "  Deployment cancelled."
    exit 0
  fi

  # ---------------------------------------------------------------------------
  # Authenticate — runs after config so user isn't blocked before providing inputs
  # ---------------------------------------------------------------------------
  echo ""
  echo "  Authenticating..."
  if fab auth status 2>/dev/null; then
    echo "  ── ✅ Already authenticated"
  else
    echo "  ── Launching Fabric auth login..."
    if fab auth login 2>&1; then
      echo "  ── ✅ Authentication successful"
    else
      echo "  ── ❌ Authentication failed."
      echo ""
      echo "     Retry manually with one of:"
      echo "     Interactive:        fab auth login"
      echo "     Service principal:  fab auth login -u <client_id> -p <client_secret> --tenant <tenant_id>"
      echo "     Managed identity:   fab auth login --identity"
      exit 1
    fi
  fi

  # ---------------------------------------------------------------------------
  # Workspace
  # ---------------------------------------------------------------------------
  echo ""
  if fab exists "$FABRIC_WORKSPACE_NAME.Workspace" 2>/dev/null; then
    echo "  ── ✅ Workspace already exists: $FABRIC_WORKSPACE_NAME"
  else
    echo "  Creating workspace..."
    fab_mkdir "$FABRIC_WORKSPACE_NAME.Workspace" "Workspace: $FABRIC_WORKSPACE_NAME" "──"
  fi

  # Assign capacity to workspace
  if [[ -n "$FABRIC_CAPACITY_ID" ]]; then
    echo "  ── Assigning capacity..."
    if fab set "$FABRIC_WORKSPACE_NAME.Workspace" -q capacityId -i "$FABRIC_CAPACITY_ID" 2>/dev/null; then
      echo "  ── ✅ Capacity assigned"
    else
      echo "  ── ⚠️  Could not assign capacity — verify ID in portal (Admin → Capacities)"
    fi
  fi

  # ---------------------------------------------------------------------------
  # Wave 1 — Foundation + Compute
  # ---------------------------------------------------------------------------
  echo ""
  echo "  Wave 1 ─ Foundation + Compute"
  fab_mkdir "$FABRIC_WORKSPACE_NAME.Workspace/call-transcripts-lakehouse.Lakehouse" \
    "Lakehouse: call-transcripts-lakehouse" "├──"
  fab_mkdir "$FABRIC_WORKSPACE_NAME.Workspace/call-analytics-warehouse.Warehouse" \
    "Warehouse: call-analytics-warehouse" "├──"
  fab_mkdir "$FABRIC_WORKSPACE_NAME.Workspace/call-events-eventhouse.Eventhouse" \
    "Eventhouse: call-events-eventhouse" "├──"

  # Create KQL Database inside Eventhouse
  local eh_id
  eh_id=$(fab get "$FABRIC_WORKSPACE_NAME.Workspace/call-events-eventhouse.Eventhouse" --output json 2>/dev/null | grep -o '"id"\s*:\s*"[^"]*"' | head -1 | sed 's/.*"\([^"]*\)"$/\1/')
  if [[ -n "$eh_id" ]]; then
    fab_mkdir "$FABRIC_WORKSPACE_NAME.Workspace/call-events-kqldb.KQLDatabase" \
      "KQL Database: call-events-kqldb" "├──" -P "eventhouseId=$eh_id"
  else
    echo "  ├── ⚠️  KQL Database: could not retrieve Eventhouse ID — create manually in portal"
  fi

  fab_mkdir "$FABRIC_WORKSPACE_NAME.Workspace/spark-env.Environment" \
    "Environment: spark-env" "└──"

  # Publish Environment so notebooks can attach to it
  echo "  ── Publishing spark-env..."
  if fab publish "$FABRIC_WORKSPACE_NAME.Workspace/spark-env.Environment" 2>/dev/null; then
    echo "  ── ✅ Environment published"
  else
    echo "  ── ⚠️  Environment publish failed — publish manually in portal before running notebooks"
  fi

  # ---------------------------------------------------------------------------
  # Wave 2 — Ingestion
  # ---------------------------------------------------------------------------
  echo ""
  echo "  Wave 2 ─ Ingestion"
  fab_mkdir "$FABRIC_WORKSPACE_NAME.Workspace/call-stream-eventstream.Eventstream" \
    "Eventstream: call-stream-eventstream" "├──"
  fab_mkdir "$FABRIC_WORKSPACE_NAME.Workspace/crm-sync-pipeline.DataPipeline" \
    "Pipeline: crm-sync-pipeline" "└──"

  # ---------------------------------------------------------------------------
  # Wave 3 — Processing
  # ---------------------------------------------------------------------------
  echo ""
  echo "  Wave 3 ─ Processing"
  fab_mkdir "$FABRIC_WORKSPACE_NAME.Workspace/transcript-etl-notebook.Notebook" \
    "Notebook: transcript-etl-notebook" "├──"
  fab_mkdir "$FABRIC_WORKSPACE_NAME.Workspace/call-insights-kql.KQLQueryset" \
    "KQL Queryset: call-insights-kql" "└──"

  # Configure notebook → lakehouse binding
  echo "  ── Binding transcript-etl-notebook → call-transcripts-lakehouse..."
  local lh_id
  lh_id=$(fab get "$FABRIC_WORKSPACE_NAME.Workspace/call-transcripts-lakehouse.Lakehouse" --output json 2>/dev/null | grep -o '"id"\s*:\s*"[^"]*"' | head -1 | sed 's/.*"\([^"]*\)"$/\1/')
  if [[ -n "$lh_id" ]]; then
    fab set "$FABRIC_WORKSPACE_NAME.Workspace/transcript-etl-notebook.Notebook" -q lakehouse -i "{\"id\":\"$lh_id\"}" 2>&1 | cat > /dev/null && \
      echo "  ── ✅ Notebook bound to Lakehouse" || \
      echo "  ── ⚠️  Manual binding needed (set default Lakehouse in portal)"
  fi

  # ---------------------------------------------------------------------------
  # Wave 4 — Serving
  # ---------------------------------------------------------------------------
  echo ""
  echo "  Wave 4 ─ Serving"
  fab_mkdir "$FABRIC_WORKSPACE_NAME.Workspace/call-analytics-model.SemanticModel" \
    "Semantic Model: call-analytics-model" "├──"
  echo "  └── ⏭️  RT Dashboard: call-ops-rt-dash (portal-only — see manual steps)"

  # ---------------------------------------------------------------------------
  # Wave 5 — Visualization
  # ---------------------------------------------------------------------------
  echo ""
  echo "  Wave 5 ─ Visualization"
  local sm_id
  sm_id=$(fab get "$FABRIC_WORKSPACE_NAME.Workspace/call-analytics-model.SemanticModel" --output json 2>/dev/null | grep -o '"id"\s*:\s*"[^"]*"' | head -1 | sed 's/.*"\([^"]*\)"$/\1/')
  if [[ -n "$sm_id" ]]; then
    fab_mkdir "$FABRIC_WORKSPACE_NAME.Workspace/call-analytics-report.Report" \
      "Report: call-analytics-report" "├──" -P "semanticModelId=$sm_id"
  else
    fab_mkdir "$FABRIC_WORKSPACE_NAME.Workspace/call-analytics-report.Report" \
      "Report: call-analytics-report" "├──"
  fi
  echo "  └── ⏭️  Activator: call-alert-activator (portal-only — see manual steps)"

  # ---------------------------------------------------------------------------
  # Wave 6 — ML
  # ---------------------------------------------------------------------------
  echo ""
  echo "  Wave 6 ─ ML"
  fab_mkdir "$FABRIC_WORKSPACE_NAME.Workspace/transcript-ml-experiment.MLExperiment" \
    "Experiment: transcript-ml-experiment" "├──"
  fab_mkdir "$FABRIC_WORKSPACE_NAME.Workspace/transcript-ml-model.MLModel" \
    "ML Model: transcript-ml-model" "├──"
  fab_mkdir "$FABRIC_WORKSPACE_NAME.Workspace/ml-scoring-notebook.Notebook" \
    "Notebook: ml-scoring-notebook" "└──"

  # Bind scoring notebook to lakehouse
  if [[ -n "$lh_id" ]]; then
    fab set "$FABRIC_WORKSPACE_NAME.Workspace/ml-scoring-notebook.Notebook" -q lakehouse -i "{\"id\":\"$lh_id\"}" 2>&1 | cat > /dev/null && \
      echo "  ── ✅ Scoring notebook bound to Lakehouse" || \
      echo "  ── ⚠️  Manual binding needed for ml-scoring-notebook"
  fi

  # ---------------------------------------------------------------------------
  # Summary
  # ---------------------------------------------------------------------------
  echo ""
  echo "┌──────────────────────────────────────────────────────────────────┐"
  echo "│  DEPLOYMENT SUMMARY                                              │"
  echo "└──────────────────────────────────────────────────────────────────┘"
  echo ""
  printf "%b\n" "$DEPLOY_LOG"
  echo ""
  echo "  Created: $DEPLOY_CREATED  |  Already existed: $DEPLOY_EXISTS  |  Failed: $DEPLOY_FAILED"

  echo ""
  echo "┌──────────────────────────────────────────────────────────────────┐"
  echo "│  MANUAL STEPS REQUIRED                                           │"
  echo "└──────────────────────────────────────────────────────────────────┘"
  echo ""
  echo "  M-1: Configure telephony/transcription source in call-stream-eventstream"
  echo "  M-2: Set up Dataverse Fabric Link for CRM entity sync"
  echo "  M-3: Configure Activator alert thresholds for queue SLA"
  echo "  M-4: Build Real-Time Dashboard tiles in portal (call-ops-rt-dash)"
  echo "  M-5: Configure Activator rules in portal (call-alert-activator)"
  echo ""

  # ---------------------------------------------------------------------------
  # Post-Deployment Metadata
  # ---------------------------------------------------------------------------
  echo "┌──────────────────────────────────────────────────────────────────┐"
  echo "│  POST-DEPLOYMENT METADATA                                       │"
  echo "└──────────────────────────────────────────────────────────────────┘"
  echo ""

  local ws_json
  ws_json=$(fab get "$FABRIC_WORKSPACE_NAME.Workspace" --output json 2>/dev/null || echo "{}")
  local workspace_id
  workspace_id=$(echo "$ws_json" | grep -o '"id"\s*:\s*"[^"]*"' | head -1 | sed 's/.*"id"\s*:\s*"\([^"]*\)".*/\1/')
  workspace_id="${workspace_id:-(unavailable)}"
  echo "  Workspace ID:   $workspace_id"

  local auth_json
  auth_json=$(fab auth status --output json 2>/dev/null || echo "{}")
  local tenant_id
  tenant_id=$(echo "$auth_json" | grep -o '"tenantId"\s*:\s*"[^"]*"' | head -1 | sed 's/.*"tenantId"\s*:\s*"\([^"]*\)".*/\1/')
  tenant_id="${tenant_id:-(unavailable)}"
  echo "  Tenant ID:      $tenant_id"

  local portal_base="https://app.fabric.microsoft.com/groups/$workspace_id"
  echo "  Workspace URL:  $portal_base"
  echo ""

  echo "  Item Details:"
  local items_json
  items_json=$(fab ls "$FABRIC_WORKSPACE_NAME.Workspace" --output json 2>/dev/null || echo "[]")
  echo "$items_json" | grep -o '"displayName"\s*:\s*"[^"]*"\|"id"\s*:\s*"[^"]*"' | paste - - | while read -r line; do
    local item_name item_id
    item_name=$(echo "$line" | sed 's/.*"displayName"\s*:\s*"\([^"]*\)".*/\1/')
    item_id=$(echo "$line" | sed 's/.*"id"\s*:\s*"\([^"]*\)".*/\1/')
    echo "  ├── $item_name  →  ID: $item_id"
  done
  echo ""
  echo "  ℹ️  Save these IDs — they are required for CI/CD parameterization"
  echo "     and fabric-cicd library configuration."
}

main "$@"
