# =============================================================================
# Fabric Task Flows — Deploy Script (PowerShell)
# Generated by @fabric-engineer
#
# Project:   Agent Assist Telco
# Task Flow: lambda
# Generated: 2026-03-07
# =============================================================================
$ErrorActionPreference = "Stop"

# ---------------------------------------------------------------------------
# Brand Banner
# ---------------------------------------------------------------------------
function Print-Banner {
  param(
    [string]$ProjectName = "Project",
    [string]$TaskFlow = "unknown",
    [string]$Mode = "Deploy"
  )

  Write-Host ""
  Write-Host "╔══════════════════════════════════════════════════════════════════╗"
  Write-Host "║                                                                  ║"
  Write-Host "║        /@@@@@@@@@@@@/  ┌──────────────────────────────────────┐  ║"
  Write-Host "║       /@@@@@@@@@@@@/   │ F A B R I C   T A S K   F L O W S    │  ║"
  Write-Host "║      /@@@@@@@@@/       │ ──────────────────────────────────── │  ║"
  Write-Host "║     /@@@@@@/           │ Deploy Microsoft Fabric              │  ║"
  Write-Host "║    /@@@@@@/            │ architectures to production          │  ║"
  Write-Host "║                        └──────────────────────────────────────┘  ║"
  Write-Host "║                                                                  ║"
  Write-Host ("║  Project:   {0,-52} ║" -f $ProjectName)
  Write-Host ("║  Task Flow: {0,-52} ║" -f $TaskFlow)
  Write-Host ("║  Mode:      {0,-52} ║" -f $Mode)
  Write-Host "║                                                                  ║"
  Write-Host "╚══════════════════════════════════════════════════════════════════╝"
  Write-Host ""
}

# ---------------------------------------------------------------------------
# Configuration
# ---------------------------------------------------------------------------
$ProjectName = "Agent Assist Telco"
$TaskFlow = "lambda"

# ---------------------------------------------------------------------------
# Interactive prompts (with env var fallbacks)
# ---------------------------------------------------------------------------
function Prompt-Value {
  param(
    [string]$EnvVarName,
    [string]$PromptText,
    [string]$DefaultValue = "",
    [switch]$Optional
  )

  $envValue = [System.Environment]::GetEnvironmentVariable($EnvVarName)
  if ($envValue) { return $envValue }

  if ($DefaultValue) {
    $input = Read-Host "  ? $PromptText (Enter = $DefaultValue, or type to rename)"
    if ([string]::IsNullOrWhiteSpace($input)) { return $DefaultValue }
    return $input
  } elseif ($Optional) {
    $input = Read-Host "  ? $PromptText (optional, Enter to skip)"
    if ([string]::IsNullOrWhiteSpace($input)) { return "" }
    return $input
  } else {
    return Read-Host "  ? $PromptText"
  }
}

function Fab-Mkdir {
  param(
    [string]$Path,
    [string]$Label,
    [string]$TreeChar = "├──",
    [string[]]$ExtraArgs = @(),
    [int]$MaxRetries = 3
  )

  fab exists "$Path" 2>$null | Out-Null
  if ($LASTEXITCODE -eq 0) {
    Write-Host "  $TreeChar ✅ $Label (already exists)"
    $script:DeployResults += @{ Label = $Label; Status = "exists" }
    return
  }

  for ($attempt = 1; $attempt -le $MaxRetries; $attempt++) {
    $allArgs = @("mkdir", $Path) + $ExtraArgs
    $errOutput = & fab @allArgs 2>&1
    if ($LASTEXITCODE -eq 0) {
      Write-Host "  $TreeChar ✅ $Label"
      $script:DeployResults += @{ Label = $Label; Status = "created" }
      return
    }
    if ($attempt -lt $MaxRetries) {
      $wait = $attempt * 10
      Write-Host "  $TreeChar ⚠️  $Label (attempt $attempt failed, retrying in ${wait}s...)"
      Write-Host "         Error: $errOutput"
      Start-Sleep -Seconds $wait
    }
  }

  Write-Host "  $TreeChar ❌ $Label (failed after $MaxRetries attempts)"
  Write-Host "         Error: $errOutput"
  $script:DeployResults += @{ Label = $Label; Status = "failed" }
  throw "Deployment failed: $Label"
}

# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------
function Main {
  Print-Banner -ProjectName $ProjectName -TaskFlow $TaskFlow -Mode "Deploy to Fabric"

  # Preflight: CLI only
  Write-Host "  Checking prerequisites..."
  $fabCmd = Get-Command fab -ErrorAction SilentlyContinue
  if (-not $fabCmd) {
    Write-Host "  ❌ Fabric CLI (fab) not found."
    Write-Host "     Install with: pip install ms-fabric-cli"
    return
  }
  Write-Host "  ── ✅ Fabric CLI found"
  Write-Host ""

  $script:DeployResults = @()

  Write-Host "┌──────────────────────────────────────────────────────────────────┐"
  Write-Host "│  CONFIGURATION                                                   │"
  Write-Host "│  Fill in the values below or set as environment variables.       │"
  Write-Host "└──────────────────────────────────────────────────────────────────┘"
  Write-Host ""

  $WorkspaceName = Prompt-Value -EnvVarName "FABRIC_WORKSPACE_NAME" -PromptText "Workspace name" -DefaultValue "agent-assist-telco-dev"
  $CapacityId = Prompt-Value -EnvVarName "FABRIC_CAPACITY_ID" -PromptText "Fabric capacity ID (GUID from portal → Capacities)"

  # Task-flow-specific prompts
  $EventHubNamespace = Prompt-Value -EnvVarName "EVENT_HUB_NAMESPACE" -PromptText "Event Hub namespace (for telephony transcription stream)"
  if (-not $EventHubNamespace) {
    Write-Host "  ⚠️  No Event Hub namespace — Eventstream will be created but cannot ingest data"
  }
  $DataverseEnv = Prompt-Value -EnvVarName "DATAVERSE_ENV" -PromptText "Dataverse environment URL (for CRM sync)"
  if (-not $DataverseEnv) {
    Write-Host "  ⚠️  No Dataverse URL — Pipeline will be created but CRM sync won't function"
  }

  Write-Host ""
  Write-Host "┌──────────────────────────────────────────────────────────────────┐"
  Write-Host "│  DEPLOYMENT PLAN                                                 │"
  Write-Host ("│{0,-66}│" -f "  Task flow: lambda  |  Items: 15  |  Waves: 6")
  Write-Host "└──────────────────────────────────────────────────────────────────┘"
  Write-Host ""
  Write-Host "  Wave 1 — Foundation + Compute"
  Write-Host "  ├── ☐ Lakehouse:   call-transcripts-lakehouse"
  Write-Host "  ├── ☐ Warehouse:   call-analytics-warehouse"
  Write-Host "  ├── ☐ Eventhouse:  call-events-eventhouse"
  Write-Host "  └── ☐ Environment: spark-env"
  Write-Host ""
  Write-Host "  Wave 2 — Ingestion"
  Write-Host "  ├── ☐ Eventstream: call-stream-eventstream"
  Write-Host "  └── ☐ Pipeline:    crm-sync-pipeline"
  Write-Host ""
  Write-Host "  Wave 3 — Processing"
  Write-Host "  ├── ☐ Notebook:     transcript-etl-notebook"
  Write-Host "  └── ☐ KQL Queryset: call-insights-kql"
  Write-Host ""
  Write-Host "  Wave 4 — Serving"
  Write-Host "  ├── ☐ Semantic Model: call-analytics-model"
  Write-Host "  └── ☐ RT Dashboard:  call-ops-rt-dash (portal)"
  Write-Host ""
  Write-Host "  Wave 5 — Visualization"
  Write-Host "  ├── ☐ Report:    call-analytics-report"
  Write-Host "  └── ☐ Activator: call-alert-activator (portal)"
  Write-Host ""
  Write-Host "  Wave 6 — ML"
  Write-Host "  ├── ☐ Experiment: transcript-ml-experiment"
  Write-Host "  ├── ☐ ML Model:   transcript-ml-model"
  Write-Host "  └── ☐ Notebook:   ml-scoring-notebook"
  Write-Host ""

  $confirm = Read-Host "  ? Proceed with deployment? [Y/n]"
  if ($confirm -and $confirm -notmatch "^[Yy]") {
    Write-Host "  Deployment cancelled."
    return
  }

  # ---------------------------------------------------------------------------
  # Authenticate — runs after config so user isn't blocked before providing inputs
  # ---------------------------------------------------------------------------
  Write-Host ""
  Write-Host "  Authenticating..."
  fab auth status 2>$null | Out-Null
  if ($LASTEXITCODE -eq 0) {
    Write-Host "  ── ✅ Already authenticated"
  } else {
    Write-Host "  ── Launching Fabric auth login..."
    fab auth login 2>&1 | Out-Null
    if ($LASTEXITCODE -eq 0) {
      Write-Host "  ── ✅ Authentication successful"
    } else {
      Write-Host "  ── ❌ Authentication failed."
      Write-Host ""
      Write-Host "     Retry manually with one of:"
      Write-Host "     Interactive:        fab auth login"
      Write-Host "     Service principal:  fab auth login -u <client_id> -p <client_secret> --tenant <tenant_id>"
      Write-Host "     Managed identity:   fab auth login --identity"
      return
    }
  }

  # ---------------------------------------------------------------------------
  # Workspace
  # ---------------------------------------------------------------------------
  Write-Host ""
  fab exists "$WorkspaceName.Workspace" 2>$null | Out-Null
  if ($LASTEXITCODE -eq 0) {
    Write-Host "  ── ✅ Workspace already exists: $WorkspaceName"
  } else {
    Write-Host "  Creating workspace..."
    Fab-Mkdir -Path "$WorkspaceName.Workspace" -Label "Workspace: $WorkspaceName" -TreeChar "──"
  }

  # Assign capacity to workspace
  if ($CapacityId) {
    Write-Host "  ── Assigning capacity..."
    fab set "$WorkspaceName.Workspace" -q capacityId -i "$CapacityId" 2>$null | Out-Null
    if ($LASTEXITCODE -eq 0) {
      Write-Host "  ── ✅ Capacity assigned"
    } else {
      Write-Host "  ── ⚠️  Could not assign capacity — verify ID in portal (Admin → Capacities)"
    }
  }

  # ---------------------------------------------------------------------------
  # Wave 1 — Foundation + Compute
  # ---------------------------------------------------------------------------
  Write-Host ""
  Write-Host "  Wave 1 — Foundation + Compute"
  Fab-Mkdir -Path "$WorkspaceName.Workspace/call-transcripts-lakehouse.Lakehouse" `
    -Label "Lakehouse: call-transcripts-lakehouse" -TreeChar "├──"
  Fab-Mkdir -Path "$WorkspaceName.Workspace/call-analytics-warehouse.Warehouse" `
    -Label "Warehouse: call-analytics-warehouse" -TreeChar "├──"
  Fab-Mkdir -Path "$WorkspaceName.Workspace/call-events-eventhouse.Eventhouse" `
    -Label "Eventhouse: call-events-eventhouse" -TreeChar "├──"

  # Create KQL Database inside Eventhouse
  try {
    $ehInfo = fab get "$WorkspaceName.Workspace/call-events-eventhouse.Eventhouse" --output json 2>$null | ConvertFrom-Json
    if ($ehInfo.id) {
      Fab-Mkdir -Path "$WorkspaceName.Workspace/call-events-kqldb.KQLDatabase" `
        -Label "KQL Database: call-events-kqldb" -TreeChar "├──" `
        -ExtraArgs @("-P", "eventhouseId=$($ehInfo.id)")
    } else {
      Write-Host "  ├── ⚠️  KQL Database: could not retrieve Eventhouse ID — create manually in portal"
    }
  } catch {
    Write-Host "  ├── ⚠️  KQL Database: could not retrieve Eventhouse ID — create manually in portal"
  }

  Fab-Mkdir -Path "$WorkspaceName.Workspace/spark-env.Environment" `
    -Label "Environment: spark-env" -TreeChar "└──"

  # Publish Environment so notebooks can attach to it
  Write-Host "  ── Publishing spark-env..."
  fab publish "$WorkspaceName.Workspace/spark-env.Environment" 2>$null | Out-Null
  if ($LASTEXITCODE -eq 0) {
    Write-Host "  ── ✅ Environment published"
  } else {
    Write-Host "  ── ⚠️  Environment publish failed — publish manually in portal before running notebooks"
  }

  # ---------------------------------------------------------------------------
  # Wave 2 — Ingestion
  # ---------------------------------------------------------------------------
  Write-Host ""
  Write-Host "  Wave 2 — Ingestion"
  Fab-Mkdir -Path "$WorkspaceName.Workspace/call-stream-eventstream.Eventstream" `
    -Label "Eventstream: call-stream-eventstream" -TreeChar "├──"
  Fab-Mkdir -Path "$WorkspaceName.Workspace/crm-sync-pipeline.DataPipeline" `
    -Label "Pipeline: crm-sync-pipeline" -TreeChar "└──"

  # ---------------------------------------------------------------------------
  # Wave 3 — Processing
  # ---------------------------------------------------------------------------
  Write-Host ""
  Write-Host "  Wave 3 — Processing"
  Fab-Mkdir -Path "$WorkspaceName.Workspace/transcript-etl-notebook.Notebook" `
    -Label "Notebook: transcript-etl-notebook" -TreeChar "├──"
  Fab-Mkdir -Path "$WorkspaceName.Workspace/call-insights-kql.KQLQueryset" `
    -Label "KQL Queryset: call-insights-kql" -TreeChar "└──"

  # Bind notebook to lakehouse
  Write-Host "  ── Binding transcript-etl-notebook → call-transcripts-lakehouse..."
  try {
    $lhInfo = fab get "$WorkspaceName.Workspace/call-transcripts-lakehouse.Lakehouse" --output json 2>$null | ConvertFrom-Json
    if ($lhInfo.id) {
      $lhJson = "{`"id`":`"$($lhInfo.id)`"}"
      fab set "$WorkspaceName.Workspace/transcript-etl-notebook.Notebook" -q lakehouse -i $lhJson 2>&1 | Out-Null
      Write-Host "  ── ✅ Notebook bound to Lakehouse"
    }
  } catch {
    Write-Host "  ── ⚠️  Manual binding needed (set default Lakehouse in portal)"
  }

  # ---------------------------------------------------------------------------
  # Wave 4 — Serving
  # ---------------------------------------------------------------------------
  Write-Host ""
  Write-Host "  Wave 4 — Serving"
  Fab-Mkdir -Path "$WorkspaceName.Workspace/call-analytics-model.SemanticModel" `
    -Label "Semantic Model: call-analytics-model" -TreeChar "├──"
  Write-Host "  └── ⏭️  RT Dashboard: call-ops-rt-dash (portal-only — see manual steps)"

  # ---------------------------------------------------------------------------
  # Wave 5 — Visualization
  # ---------------------------------------------------------------------------
  Write-Host ""
  Write-Host "  Wave 5 — Visualization"
  try {
    $smInfo = fab get "$WorkspaceName.Workspace/call-analytics-model.SemanticModel" --output json 2>$null | ConvertFrom-Json
    if ($smInfo.id) {
      Fab-Mkdir -Path "$WorkspaceName.Workspace/call-analytics-report.Report" `
        -Label "Report: call-analytics-report" -TreeChar "├──" `
        -ExtraArgs @("-P", "semanticModelId=$($smInfo.id)")
    } else {
      Fab-Mkdir -Path "$WorkspaceName.Workspace/call-analytics-report.Report" `
        -Label "Report: call-analytics-report" -TreeChar "├──"
    }
  } catch {
    Fab-Mkdir -Path "$WorkspaceName.Workspace/call-analytics-report.Report" `
      -Label "Report: call-analytics-report" -TreeChar "├──"
  }
  Write-Host "  └── ⏭️  Activator: call-alert-activator (portal-only — see manual steps)"

  # ---------------------------------------------------------------------------
  # Wave 6 — ML
  # ---------------------------------------------------------------------------
  Write-Host ""
  Write-Host "  Wave 6 — ML"
  Fab-Mkdir -Path "$WorkspaceName.Workspace/transcript-ml-experiment.MLExperiment" `
    -Label "Experiment: transcript-ml-experiment" -TreeChar "├──"
  Fab-Mkdir -Path "$WorkspaceName.Workspace/transcript-ml-model.MLModel" `
    -Label "ML Model: transcript-ml-model" -TreeChar "├──"
  Fab-Mkdir -Path "$WorkspaceName.Workspace/ml-scoring-notebook.Notebook" `
    -Label "Notebook: ml-scoring-notebook" -TreeChar "└──"

  # Bind scoring notebook to lakehouse
  try {
    if ($lhInfo.id) {
      fab set "$WorkspaceName.Workspace/ml-scoring-notebook.Notebook" -q lakehouse -i $lhJson 2>&1 | Out-Null
      Write-Host "  ── ✅ Scoring notebook bound to Lakehouse"
    }
  } catch {
    Write-Host "  ── ⚠️  Manual binding needed for ml-scoring-notebook"
  }

  # ---------------------------------------------------------------------------
  # Summary
  # ---------------------------------------------------------------------------
  Write-Host ""
  Write-Host "┌──────────────────────────────────────────────────────────────────┐"
  Write-Host "│  DEPLOYMENT SUMMARY                                              │"
  Write-Host "└──────────────────────────────────────────────────────────────────┘"
  Write-Host ""
  $created = ($script:DeployResults | Where-Object { $_.Status -eq "created" }).Count
  $existed = ($script:DeployResults | Where-Object { $_.Status -eq "exists" }).Count
  $failed  = ($script:DeployResults | Where-Object { $_.Status -eq "failed" }).Count
  foreach ($r in $script:DeployResults) {
    $icon = switch ($r.Status) { "created" { "✅ Created" } "exists" { "✅ Exists " } "failed" { "❌ Failed " } default { "⏭️  Skipped" } }
    Write-Host "  $icon  $($r.Label)"
  }
  Write-Host ""
  Write-Host "  Created: $created  |  Already existed: $existed  |  Failed: $failed"

  Write-Host ""
  Write-Host "┌──────────────────────────────────────────────────────────────────┐"
  Write-Host "│  MANUAL STEPS REQUIRED                                           │"
  Write-Host "└──────────────────────────────────────────────────────────────────┘"
  Write-Host ""
  Write-Host "  M-1: Configure telephony/transcription source in call-stream-eventstream"
  Write-Host "  M-2: Set up Dataverse Fabric Link for CRM entity sync"
  Write-Host "  M-3: Configure Activator alert thresholds for queue SLA"
  Write-Host "  M-4: Build Real-Time Dashboard tiles in portal (call-ops-rt-dash)"
  Write-Host "  M-5: Configure Activator rules in portal (call-alert-activator)"
  Write-Host ""

  # ---------------------------------------------------------------------------
  # Post-Deployment Metadata
  # ---------------------------------------------------------------------------
  Write-Host "┌──────────────────────────────────────────────────────────────────┐"
  Write-Host "│  POST-DEPLOYMENT METADATA                                       │"
  Write-Host "└──────────────────────────────────────────────────────────────────┘"
  Write-Host ""

  $wsInfo = fab get "$WorkspaceName.Workspace" --output json 2>$null | ConvertFrom-Json
  $WorkspaceId = if ($wsInfo.id) { $wsInfo.id } else { "(unavailable)" }
  Write-Host "  Workspace ID:   $WorkspaceId"

  $authInfo = fab auth status --output json 2>$null | ConvertFrom-Json
  $TenantId = if ($authInfo.tenantId) { $authInfo.tenantId } else { "(unavailable)" }
  Write-Host "  Tenant ID:      $TenantId"

  $portalBase = "https://app.fabric.microsoft.com/groups/$WorkspaceId"
  Write-Host "  Workspace URL:  $portalBase"
  Write-Host ""

  Write-Host "  Item Details:"
  foreach ($r in $script:DeployResults) {
    if ($r.Status -eq "created" -or $r.Status -eq "exists") {
      $itemName = ($r.Label -split ":\s*", 2)[-1].Trim()
      try {
        $itemInfo = fab get "$WorkspaceName.Workspace/$itemName" --output json 2>$null | ConvertFrom-Json
        $itemId = if ($itemInfo.id) { $itemInfo.id } else { "-" }
      } catch { $itemId = "-" }
      Write-Host "  ├── $($r.Label)  →  ID: $itemId"
    }
  }
  Write-Host ""
  Write-Host "  ℹ️  Save these IDs — they are required for CI/CD parameterization"
  Write-Host "     and fabric-cicd library configuration."
}

Main
