#!/usr/bin/env python3
"""
Fabric Task Flows — Deploy Script (Python)
Generated by @fabric-engineer

Project:   Agent Assist Telco
Task Flow: lambda
Generated: 2026-03-07

Usage:
    python deploy-agent-assist-telco.py
    python deploy-agent-assist-telco.py --spn-auth
    python deploy-agent-assist-telco.py --workspace my-ws --capacity my-cap
"""

import argparse
import os
import sys

# Add _shared to path for fabric_deploy utility
sys.path.insert(0, os.path.join(os.path.dirname(__file__), "..", "..", "_shared"))
from fabric_deploy import (
    FabricDeployer, print_banner, prompt_value,
    run_fab, check_auth,
)


def main():
    parser = argparse.ArgumentParser(
        description="Deploy Agent Assist Telco (lambda architecture) to Microsoft Fabric"
    )
    parser.add_argument("--workspace", default=os.getenv("FABRIC_WORKSPACE_NAME", "agent-assist-telco-dev"))
    parser.add_argument("--capacity", default=os.getenv("FABRIC_CAPACITY", ""))
    parser.add_argument("--spn-auth", action="store_true", default=False)
    parser.add_argument("--yes", "-y", action="store_true", help="Skip confirmation prompt")
    args = parser.parse_args()

    print_banner("Agent Assist Telco", "lambda")

    # ── Configuration ──────────────────────────────────────────────
    if not args.workspace:
        args.workspace = prompt_value("FABRIC_WORKSPACE_NAME", "Workspace name", "agent-assist-telco-dev")
    if not args.capacity:
        args.capacity = prompt_value("FABRIC_CAPACITY", "Fabric capacity name")

    source_connection_string = prompt_value("SOURCE_CONNECTION_STRING", "Source database connection string (e.g., SQL Server, PostgreSQL — used by Copy Job)", optional=True)
    if not source_connection_string:
        print("  ⚠️  No Connection to source database — related items will be created but not configured")
    event_hub_namespace = prompt_value("EVENT_HUB_NAMESPACE", "Event Hub namespace (Azure Event Hubs that streams events into Fabric)", optional=True)
    if not event_hub_namespace:
        print("  ⚠️  No Azure Event Hub namespace for streaming — related items will be created but not configured")
    event_hub_consumer_group = prompt_value("EVENT_HUB_CONSUMER_GROUP", "Event Hub consumer group (isolates this pipeline's read position — use $Default if unsure)")

    # ── Deployment Plan ─────────────────────────────────────────────
    print("┌──────────────────────────────────────────────────────────────────┐")
    print("│  DEPLOYMENT PLAN                                                 │")
    print("│  {:<66}│".format("  Task flow: lambda  |  Items: 16  |  Waves: 7"))
    print("└──────────────────────────────────────────────────────────────────┘")
    print()
    print("  Wave 1 — Foundation + Compute")
    print("  ├── ☐ Lakehouse: call-transcripts-lakehouse")
    print("  ├── ☐ Warehouse: call-analytics-warehouse")
    print("  ├── ☐ Eventhouse: call-events-eventhouse")
    print("  └── ☐ Environment: spark-env")
    print()
    print("  Wave 2 — Ingestion")
    print("  ├── ☐ Eventstream: call-stream-eventstream")
    print("  └── ☐ Data Pipeline: crm-sync-pipeline")
    print()
    print("  Wave 3 — Processing")
    print("  ├── ☐ Notebook: transcript-etl-notebook")
    print("  └── ☐ KQL Queryset: call-insights-kql")
    print()
    print("  Wave 4 — Serving")
    print("  ├── ☐ Semantic Model: call-analytics-model")
    print("  └── ☐ [MANUAL] Real-Time Dashboard: call-ops-rt-dash")
    print()
    print("  Wave 5 — Visualization")
    print("  ├── ☐ Report: call-analytics-report")
    print("  └── ☐ [MANUAL] Activator: call-alert-activator")
    print()
    print("  Wave 6 — ML")
    print("  ├── ☐ ML Experiment: transcript-ml-experiment")
    print("  ├── ☐ ML Model: transcript-ml-model")
    print("  └── ☐ Notebook: ml-scoring-notebook")
    print()

    if not args.yes:
        confirm = input("  ? Proceed with deployment? [Y/n]: ").strip() or "Y"
        if confirm.upper() != "Y":
            print("  Deployment cancelled.")
            return

    # ── Authenticate ────────────────────────────────────────────────
    deployer = FabricDeployer(workspace=args.workspace, capacity=args.capacity)
    deployer.authenticate(spn=args.spn_auth)

    # ── Workspace ────────────────────────────────────────────────────
    workspace_id = deployer.create_workspace()

    # ── Wave 1 — Foundation + Compute ──────────────────────────────────────
    print("\n  Wave 1 — Foundation + Compute")
    call_transcripts_lakehouse_id = deployer.create_item("call-transcripts-lakehouse", "Lakehouse", "├──", enableSchemas="true")
    call_analytics_warehouse_id = deployer.create_item("call-analytics-warehouse", "Warehouse", "├──")
    call_events_eventhouse_id = deployer.create_item("call-events-eventhouse", "Eventhouse", "├──")
    eh_id = call_events_eventhouse_id or ""
    spark_env_id = deployer.create_item("spark-env", "Environment", "└──")

    # ── Wave 2 — Ingestion ──────────────────────────────────────
    print("\n  Wave 2 — Ingestion")
    call_stream_eventstream_id = deployer.create_item("call-stream-eventstream", "Eventstream", "├──")
    crm_sync_pipeline_id = deployer.create_item("crm-sync-pipeline", "DataPipeline", "└──")

    # ── Wave 3 — Processing ──────────────────────────────────────
    print("\n  Wave 3 — Processing")
    transcript_etl_notebook_id = deployer.create_item("transcript-etl-notebook", "Notebook", "├──")
    call_insights_kql_id = deployer.create_item("call-insights-kql", "KQLQueryset", "└──")

    # ── Wave 4 — Serving ──────────────────────────────────────
    print("\n  Wave 4 — Serving")
    call_analytics_model_id = deployer.create_item("call-analytics-model", "SemanticModel", "├──")
    sm_id = call_analytics_model_id or ""
    deployer.manual_step("Real-Time Dashboard: call-ops-rt-dash", "└──")

    # ── Wave 5 — Visualization ──────────────────────────────────────
    print("\n  Wave 5 — Visualization")
    call_analytics_report_id = deployer.create_item("call-analytics-report", "Report", "├──", semanticModelId=sm_id)
    deployer.manual_step("Activator: call-alert-activator", "└──")

    # ── Wave 6 — ML ──────────────────────────────────────
    print("\n  Wave 6 — ML")
    transcript_ml_experiment_id = deployer.create_item("transcript-ml-experiment", "MLExperiment", "├──")
    transcript_ml_model_id = deployer.create_item("transcript-ml-model", "MLModel", "├──")
    ml_scoring_notebook_id = deployer.create_item("ml-scoring-notebook", "Notebook", "└──")

    # ── Summary ──────────────────────────────────────────────────────
    deployer.print_summary()
    deployer.print_metadata()


if __name__ == "__main__":
    main()
