# =============================================================================
# Fabric Task Flows — Deploy Script (PowerShell)
# Generated by @fabric-engineer
#
# Project:   Agent Assist Telco
# Task Flow: lambda
# Generated: 2026-03-07
# =============================================================================
$ErrorActionPreference = "Stop"

# ---------------------------------------------------------------------------
# Brand Banner
# ---------------------------------------------------------------------------
function Print-Banner {
  param(
    [string]$ProjectName = "Project",
    [string]$TaskFlow = "unknown",
    [string]$Mode = "Deploy"
  )

  Write-Host ""
  Write-Host "╔══════════════════════════════════════════════════════════════════╗"
  Write-Host "║                                                                  ║"
  Write-Host "║        /@@@@@@@@@@@@/  ┌──────────────────────────────────────┐  ║"
  Write-Host "║       /@@@@@@@@@@@@/   │ F A B R I C   T A S K   F L O W S    │  ║"  
  Write-Host "║      /@@@@@@@@@/       │ ──────────────────────────────────── │  ║"
  Write-Host "║     /@@@@@@/           │ Deploy Microsoft Fabric              │  ║"
  Write-Host "║    /@@@@@@/            │ architectures to production          │  ║"
  Write-Host "║                        └──────────────────────────────────────┘  ║"
  Write-Host "║                                                                  ║"
  Write-Host ("║  Project:   {0,-52} ║" -f $ProjectName)
  Write-Host ("║  Task Flow: {0,-52} ║" -f $TaskFlow)
  Write-Host ("║  Mode:      {0,-52} ║" -f $Mode)
  Write-Host "║                                                                  ║"
  Write-Host "╚══════════════════════════════════════════════════════════════════╝"
  Write-Host ""
}

# ---------------------------------------------------------------------------
# Configuration
# ---------------------------------------------------------------------------
$ProjectName = "Agent Assist Telco"
$TaskFlow = "lambda"

# ---------------------------------------------------------------------------
# Interactive prompts (with env var fallbacks)
# ---------------------------------------------------------------------------
function Prompt-Value {
  param(
    [string]$EnvVarName,
    [string]$PromptText,
    [string]$DefaultValue = "",
    [switch]$Optional
  )

  $envValue = [System.Environment]::GetEnvironmentVariable($EnvVarName)
  if ($envValue) { return $envValue }

  if ($DefaultValue) {
    $input = Read-Host "  ? $PromptText (Enter = $DefaultValue, or type to rename)"
    if ([string]::IsNullOrWhiteSpace($input)) { return $DefaultValue }
    return $input
  } elseif ($Optional) {
    $input = Read-Host "  ? $PromptText (optional, Enter to skip)"
    if ([string]::IsNullOrWhiteSpace($input)) { return "" }
    return $input
  } else {
    return Read-Host "  ? $PromptText"
  }
}

function Fab-Mkdir {
  param(
    [string]$Path,
    [string]$Label,
    [string]$TreeChar = "├──",
    [string[]]$ExtraArgs = @(),
    [int]$MaxRetries = 3
  )

  # Idempotency: skip if item already exists
  $existsOut = & fab -c "exists $Path" 2>&1 | Out-String
  if ($existsOut -notmatch "does not exist") {
    Write-Host "  $TreeChar ✅ $Label (already exists)"
    $script:DeployResults += @{ Label = $Label; Status = "exists" }
    return
  }

  # Retry with backoff for transient failures
  for ($attempt = 1; $attempt -le $MaxRetries; $attempt++) {
    $extraStr = if ($ExtraArgs.Count -gt 0) { " " + ($ExtraArgs -join " ") } else { "" }
    $errOutput = & fab -c "mkdir $Path$extraStr" 2>&1 | Out-String
    if ($LASTEXITCODE -eq 0) {
      Write-Host "  $TreeChar ✅ $Label"
      $script:DeployResults += @{ Label = $Label; Status = "created" }
      return
    }
    if ($attempt -lt $MaxRetries) {
      $wait = $attempt * 10
      Write-Host "  $TreeChar ⚠️  $Label (attempt $attempt failed, retrying in ${wait}s...)"
      Write-Host "         Error: $errOutput"
      Start-Sleep -Seconds $wait
    }
  }

  Write-Host "  $TreeChar ❌ $Label (failed after $MaxRetries attempts)"
  Write-Host "         Error: $errOutput"
  $script:DeployResults += @{ Label = $Label; Status = "failed" }
  throw "Deployment failed: $Label"
}

# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------
function Main {
  Print-Banner -ProjectName $ProjectName -TaskFlow $TaskFlow -Mode "Deploy to Fabric"

  # ---------------------------------------------------------------------------
  # Preflight: CLI only (auth comes after config)
  # ---------------------------------------------------------------------------
  Write-Host "  Checking prerequisites..."
  $fabCmd = Get-Command fab -ErrorAction SilentlyContinue
  if (-not $fabCmd) {
    Write-Host "  ❌ Fabric CLI (fab) not found."
    Write-Host "     Install with: pip install ms-fabric-cli"
    return
  }
  Write-Host "  ── ✅ Fabric CLI found"
  Write-Host ""

  # Track deployment results
  $script:DeployResults = @()

  # ---------------------------------------------------------------------------
  # Configuration — collect ALL inputs before authenticating
  # ---------------------------------------------------------------------------
  Write-Host "┌──────────────────────────────────────────────────────────────────┐"
  Write-Host "│  CONFIGURATION                                                   │"
  Write-Host "│  Fill in the values below or set as environment variables.       │"
  Write-Host "└──────────────────────────────────────────────────────────────────┘"
  Write-Host ""

  $WorkspaceName = Prompt-Value -EnvVarName "FABRIC_WORKSPACE_NAME" -PromptText "Workspace name" -DefaultValue "agent-assist-telco-dev"
  $CapacityId = Prompt-Value -EnvVarName "FABRIC_CAPACITY_ID" -PromptText "Fabric capacity ID (GUID from portal → Capacities)"

  # Connection to source database
  $SourceConnectionString = Prompt-Value -EnvVarName "SOURCE_CONNECTION_STRING" -PromptText "Source database connection string (e.g., SQL Server, PostgreSQL — used by Copy Job)" -Optional
  # Azure Event Hub namespace for streaming
  $EventHubNamespace = Prompt-Value -EnvVarName "EVENT_HUB_NAMESPACE" -PromptText "Event Hub namespace (Azure Event Hubs that streams events into Fabric)" -Optional
  # Consumer group controls which reader offset Eventstream uses
  $EventHubConsumerGroup = Prompt-Value -EnvVarName "EVENT_HUB_CONSUMER_GROUP" -PromptText "Event Hub consumer group (isolates this pipeline's read position — use $Default if unsure)" -DefaultValue "$Default"

  Write-Host ""
  Write-Host "┌──────────────────────────────────────────────────────────────────┐"
  Write-Host "│  DEPLOYMENT PLAN                                                 │"
  Write-Host ("│{0,-66}│" -f "  Task flow: $TaskFlow  |  Items: 16  |  Waves: 7")
  Write-Host "└──────────────────────────────────────────────────────────────────┘"
  Write-Host ""

  Write-Host "  Wave 1 — Foundation + Compute"
  Write-Host "  ├── ☐ Lakehouse: call-transcripts-lakehouse"
  Write-Host "  ├── ☐ Warehouse: call-analytics-warehouse"
  Write-Host "  ├── ☐ Eventhouse: call-events-eventhouse"
  Write-Host "  └── ☐ Environment: spark-env"
  Write-Host ""
  Write-Host "  Wave 2 — Ingestion"
  Write-Host "  ├── ☐ Eventstream: call-stream-eventstream"
  Write-Host "  └── ☐ Data Pipeline: crm-sync-pipeline"
  Write-Host ""
  Write-Host "  Wave 3 — Processing"
  Write-Host "  ├── ☐ Notebook: transcript-etl-notebook"
  Write-Host "  └── ☐ KQL Queryset: call-insights-kql"
  Write-Host ""
  Write-Host "  Wave 4 — Serving"
  Write-Host "  ├── ☐ Semantic Model: call-analytics-model"
  Write-Host "  └── ☐ [MANUAL] Real-Time Dashboard: call-ops-rt-dash"
  Write-Host ""
  Write-Host "  Wave 5 — Visualization"
  Write-Host "  ├── ☐ Report: call-analytics-report"
  Write-Host "  └── ☐ [MANUAL] Activator: call-alert-activator"
  Write-Host ""
  Write-Host "  Wave 6 — ML"
  Write-Host "  ├── ☐ ML Experiment: transcript-ml-experiment"
  Write-Host "  ├── ☐ ML Model: transcript-ml-model"
  Write-Host "  └── ☐ Notebook: ml-scoring-notebook"
  Write-Host ""

  Write-Host ""
  $confirm = Read-Host "  ? Proceed with deployment? [Y/n]"
  if ($confirm -and $confirm -notmatch "^[Yy]") {
    Write-Host "  Deployment cancelled."
    return
  }

  # ---------------------------------------------------------------------------
  # Authenticate — verify auth; if not logged in, auto-login via browser
  # ---------------------------------------------------------------------------
  Write-Host ""
  Write-Host "  Checking authentication..."
  $authOut = & fab -c "auth status" 2>&1 | Out-String
  if ($authOut -match "Not logged in") {
    Write-Host "  ── Not authenticated — launching browser login..."
    & fab -c "auth login" 2>$null
    $authOut = & fab -c "auth status" 2>&1 | Out-String
    if ($authOut -match "Not logged in") {
      Write-Host "  ── ❌ Authentication failed."
      Write-Host ""
      Write-Host "     Run manually:  fab -c 'auth login'"
      Write-Host "     Then re-run this script."
      return
    }
  }
  Write-Host "  ── ✅ Authenticated"

  # ---------------------------------------------------------------------------
  # Workspace
  # ---------------------------------------------------------------------------
  Write-Host ""
  $wsCheck = & fab -c "exists $WorkspaceName.Workspace" 2>&1 | Out-String
  if ($wsCheck -notmatch "does not exist") {
    Write-Host "  ── ✅ Workspace already exists: $WorkspaceName"
  } else {
    Write-Host "  Creating workspace..."
    Fab-Mkdir -Path "$WorkspaceName.Workspace" -Label "Workspace: $WorkspaceName" -TreeChar "──"
  }

  # Assign capacity to workspace
  if ($CapacityId) {
    Write-Host "  ── Assigning capacity..."
    & fab -c "set $WorkspaceName.Workspace -q capacityId -i $CapacityId" 2>$null | Out-Null
    if ($LASTEXITCODE -eq 0) {
      Write-Host "  ── ✅ Capacity assigned"
    } else {
      Write-Host "  ── ⚠️  Could not assign capacity — verify ID in portal (Admin → Capacities)"
    }
  }

  # ---------------------------------------------------------------------------
  # Wave Deployment
  # ---------------------------------------------------------------------------
  # ─────────────────────────────────────────────────────────────────
  # Wave 1 — Foundation + Compute
  # ─────────────────────────────────────────────────────────────────
  Write-Host ""
  Write-Host "  Wave 1 — Foundation + Compute"
  Fab-Mkdir -Path "$WorkspaceName.Workspace/call-transcripts-lakehouse.Lakehouse" -Label "Lakehouse: call-transcripts-lakehouse" -TreeChar "├──" -ExtraArgs @("-P", "enableSchemas=true")
  Fab-Mkdir -Path "$WorkspaceName.Workspace/call-analytics-warehouse.Warehouse" -Label "Warehouse: call-analytics-warehouse" -TreeChar "├──"
  Fab-Mkdir -Path "$WorkspaceName.Workspace/call-events-eventhouse.Eventhouse" -Label "Eventhouse: call-events-eventhouse" -TreeChar "├──"
  Fab-Mkdir -Path "$WorkspaceName.Workspace/spark-env.Environment" -Label "Environment: spark-env" -TreeChar "└──"

  Write-Host "  ⏳ Waiting for Environment publish (may take 20+ min)..."
  $maxWait = 1800; $elapsed = 0
  do {
    Start-Sleep -Seconds 30; $elapsed += 30
    $envStatus = (fab get "$WorkspaceName.Workspace/spark-env.Environment" -q properties.publishStatus 2>&1)
    Write-Host "    ⏱  $([math]::Floor($elapsed/60))m elapsed — status: $envStatus"
  } while ($envStatus -ne "Published" -and $elapsed -lt $maxWait)
  if ($envStatus -ne "Published") {
    Write-Host "  ⚠️  Environment publish timed out — notebooks may fail until publish completes"
  } else {
    Write-Host "  ── ✅ Environment published"
  }

  $EventhouseId = (fab get "$WorkspaceName.Workspace/call-events-eventhouse.Eventhouse" -q id 2>&1).Trim()
  Write-Host "  ── ℹ️  Captured Eventhouse ID: $EventhouseId"

  # ─────────────────────────────────────────────────────────────────
  # Wave 2 — Ingestion
  # ─────────────────────────────────────────────────────────────────
  Write-Host ""
  Write-Host "  Wave 2 — Ingestion"
  Fab-Mkdir -Path "$WorkspaceName.Workspace/call-stream-eventstream.Eventstream" -Label "Eventstream: call-stream-eventstream" -TreeChar "├──"
  Fab-Mkdir -Path "$WorkspaceName.Workspace/crm-sync-pipeline.DataPipeline" -Label "Data Pipeline: crm-sync-pipeline" -TreeChar "└──"

  # ─────────────────────────────────────────────────────────────────
  # Wave 3 — Processing
  # ─────────────────────────────────────────────────────────────────
  Write-Host ""
  Write-Host "  Wave 3 — Processing"
  Fab-Mkdir -Path "$WorkspaceName.Workspace/transcript-etl-notebook.Notebook" -Label "Notebook: transcript-etl-notebook" -TreeChar "├──"
  Fab-Mkdir -Path "$WorkspaceName.Workspace/call-insights-kql.KQLQueryset" -Label "KQL Queryset: call-insights-kql" -TreeChar "└──"

  # Bind transcript-etl-notebook to dependencies
  $lhId = (fab get "$WorkspaceName.Workspace/call-transcripts-lakehouse.Lakehouse" -q id 2>&1).Trim()
  fab set "$WorkspaceName.Workspace/transcript-etl-notebook.Notebook" -q lakehouse -i "$lhId" 2>&1 | Out-Null
  Write-Host "  ── ✅ transcript-etl-notebook bound to lakehouse call-transcripts-lakehouse"
  $envId = (fab get "$WorkspaceName.Workspace/spark-env.Environment" -q id 2>&1).Trim()
  fab set "$WorkspaceName.Workspace/transcript-etl-notebook.Notebook" -q environment -i "$envId" 2>&1 | Out-Null
  Write-Host "  ── ✅ transcript-etl-notebook bound to environment spark-env"

  # ─────────────────────────────────────────────────────────────────
  # Wave 4 — Serving
  # ─────────────────────────────────────────────────────────────────
  Write-Host ""
  Write-Host "  Wave 4 — Serving"
  Fab-Mkdir -Path "$WorkspaceName.Workspace/call-analytics-model.SemanticModel" -Label "Semantic Model: call-analytics-model" -TreeChar "├──"
  Write-Host "  └── ⏭️  [MANUAL] Real-Time Dashboard: create via Fabric Portal"

  $SemanticModelId = (fab get "$WorkspaceName.Workspace/call-analytics-model.SemanticModel" -q id 2>&1).Trim()
  Write-Host "  ── ℹ️  Captured SemanticModel ID: $SemanticModelId"

  # ─────────────────────────────────────────────────────────────────
  # Wave 5 — Visualization
  # ─────────────────────────────────────────────────────────────────
  Write-Host ""
  Write-Host "  Wave 5 — Visualization"
  Fab-Mkdir -Path "$WorkspaceName.Workspace/call-analytics-report.Report" -Label "Report: call-analytics-report" -TreeChar "├──" -ExtraArgs @("-P", "semanticModelId=$SemanticModelId")
  Write-Host "  └── ⏭️  [MANUAL] Activator: create via Fabric Portal"

  # ─────────────────────────────────────────────────────────────────
  # Wave 6 — ML
  # ─────────────────────────────────────────────────────────────────
  Write-Host ""
  Write-Host "  Wave 6 — ML"
  Fab-Mkdir -Path "$WorkspaceName.Workspace/transcript-ml-experiment.MLExperiment" -Label "ML Experiment: transcript-ml-experiment" -TreeChar "├──"
  Fab-Mkdir -Path "$WorkspaceName.Workspace/transcript-ml-model.MLModel" -Label "ML Model: transcript-ml-model" -TreeChar "├──"
  Fab-Mkdir -Path "$WorkspaceName.Workspace/ml-scoring-notebook.Notebook" -Label "Notebook: ml-scoring-notebook" -TreeChar "└──"

  # Bind ml-scoring-notebook to dependencies
  $envId = (fab get "$WorkspaceName.Workspace/spark-env.Environment" -q id 2>&1).Trim()
  fab set "$WorkspaceName.Workspace/ml-scoring-notebook.Notebook" -q environment -i "$envId" 2>&1 | Out-Null
  Write-Host "  ── ✅ ml-scoring-notebook bound to environment spark-env"


  Write-Host ""
  Write-Host "┌──────────────────────────────────────────────────────────────────┐"
  Write-Host "│  DEPLOYMENT SUMMARY                                              │"
  Write-Host "└──────────────────────────────────────────────────────────────────┘"
  Write-Host ""
  $created = ($script:DeployResults | Where-Object { $_.Status -eq "created" }).Count
  $existed = ($script:DeployResults | Where-Object { $_.Status -eq "exists" }).Count
  $failed  = ($script:DeployResults | Where-Object { $_.Status -eq "failed" }).Count
  foreach ($r in $script:DeployResults) {
    $icon = switch ($r.Status) { "created" { "✅ Created" } "exists" { "✅ Exists " } "failed" { "❌ Failed " } default { "⏭️  Skipped" } }
    Write-Host "  $icon  $($r.Label)"
  }
  Write-Host ""
  Write-Host "  Created: $created  |  Already existed: $existed  |  Failed: $failed"

  # ---------------------------------------------------------------------------
  # Post-Deployment Metadata
  # ---------------------------------------------------------------------------
  Write-Host ""
  Write-Host "┌──────────────────────────────────────────────────────────────────┐"
  Write-Host "│  POST-DEPLOYMENT METADATA                                       │"
  Write-Host "└──────────────────────────────────────────────────────────────────┘"
  Write-Host ""

  # Workspace ID
  $wsJson = & fab -c "get $WorkspaceName.Workspace --output json" 2>$null | Out-String
  try { $wsInfo = $wsJson | ConvertFrom-Json } catch { $wsInfo = $null }
  $WorkspaceId = if ($wsInfo.id) { $wsInfo.id } else { "(unavailable)" }
  Write-Host "  Workspace ID:   $WorkspaceId"

  # Tenant ID
  $authJson = & fab -c "auth status --output json" 2>$null | Out-String
  try { $authInfo = $authJson | ConvertFrom-Json } catch { $authInfo = $null }
  $TenantId = if ($authInfo.tenantId) { $authInfo.tenantId } else { "(unavailable)" }
  Write-Host "  Tenant ID:      $TenantId"

  # Portal URL
  $portalBase = "https://app.fabric.microsoft.com/groups/$WorkspaceId"
  Write-Host "  Workspace URL:  $portalBase"
  Write-Host ""

  # Per-item IDs
  Write-Host "  Item Details:"
  foreach ($r in $script:DeployResults) {
    if ($r.Status -eq "created" -or $r.Status -eq "exists") {
      $itemName = ($r.Label -split ":\s*", 2)[-1].Trim()
      $itemJson = & fab -c "get $WorkspaceName.Workspace/$itemName --output json" 2>$null | Out-String
      try { $itemInfo = $itemJson | ConvertFrom-Json } catch { $itemInfo = $null }
      $itemId = if ($itemInfo.id) { $itemInfo.id } else { "-" }
      Write-Host "  ├── $($r.Label)  →  ID: $itemId"
    }
  }
  Write-Host ""
  Write-Host "  ℹ️  Save these IDs — they are required for CI/CD parameterization"
  Write-Host "     and fabric-cicd library configuration."
}

Main
