#!/usr/bin/env bash
# =============================================================================
# Fabric Task Flows — Deploy Script
# Generated by @fabric-engineer
#
# Project:   Agent Assist Telco
# Task Flow: lambda
# Generated: 2026-03-07
# =============================================================================
set -euo pipefail

# ---------------------------------------------------------------------------
# Brand Banner
# ---------------------------------------------------------------------------
print_banner() {
  local project_name="${1:-Project}"
  local task_flow="${2:-unknown}"
  local mode="${3:-Deploy}"

  echo ""
  echo "╔══════════════════════════════════════════════════════════════════╗"
  echo "║                                                                  ║"
  echo "║        /@@@@@@@@@@@@/  ┌──────────────────────────────────────┐  ║"
  echo "║       /@@@@@@@@@@@@/   │ F A B R I C   T A S K   F L O W S    │  ║"
  echo "║      /@@@@@@@@@/       │ ──────────────────────────────────── │  ║"
  echo "║     /@@@@@@/           │ Deploy Microsoft Fabric              │  ║"
  echo "║    /@@@@@@/            │ architectures to production          │  ║"
  echo "║                        └──────────────────────────────────────┘  ║"
  echo "║                                                                  ║"
  printf "║  Project:   %-52s ║\n" "$project_name"
  printf "║  Task Flow: %-52s ║\n" "$task_flow"
  printf "║  Mode:      %-52s ║\n" "$mode"
  echo "║                                                                  ║"
  echo "╚══════════════════════════════════════════════════════════════════╝"
  echo ""
}

# ---------------------------------------------------------------------------
# Configuration — fill these or set as environment variables
# ---------------------------------------------------------------------------
PROJECT_NAME="Agent Assist Telco"
TASK_FLOW="lambda"

# ---------------------------------------------------------------------------
# Interactive prompts (with env var fallbacks)
# ---------------------------------------------------------------------------
prompt_value() {
  local var_name="$1"
  local prompt_text="$2"
  local default_value="${3:-}"
  local optional="${4:-}"
  local env_value="${!var_name:-}"

  if [[ -n "$env_value" ]]; then
    echo "$env_value"
    return
  fi

  if [[ -n "$default_value" ]]; then
    read -rp "  ? $prompt_text (Enter = $default_value, or type to rename): " input
    echo "${input:-$default_value}"
  elif [[ "$optional" == "optional" ]]; then
    read -rp "  ? $prompt_text (optional, Enter to skip): " input
    echo "$input"
  else
    read -rp "  ? $prompt_text: " input
    echo "$input"
  fi
}

DEPLOY_CREATED=0
DEPLOY_EXISTS=0
DEPLOY_FAILED=0
DEPLOY_LOG=""

fab_mkdir() {
  local path="$1"
  local label="$2"
  local tree_char="${3:-├──}"
  shift 3 2>/dev/null || true
  local extra_args=("$@")
  local max_retries=3
  local err_output

  # Idempotency: skip if item already exists
  if fab exists "$path" 2>/dev/null; then
    echo "  $tree_char ✅ $label (already exists)"
    DEPLOY_EXISTS=$((DEPLOY_EXISTS + 1))
    DEPLOY_LOG="${DEPLOY_LOG}\n  ✅ Exists   $label"
    return
  fi

  # Retry with backoff for transient failures
  for attempt in $(seq 1 $max_retries); do
    err_output=$(fab mkdir "$path" "${extra_args[@]}" 2>&1)
    if [ $? -eq 0 ]; then
      echo "  $tree_char ✅ $label"
      DEPLOY_CREATED=$((DEPLOY_CREATED + 1))
      DEPLOY_LOG="${DEPLOY_LOG}\n  ✅ Created  $label"
      return
    fi
    if [ "$attempt" -lt "$max_retries" ]; then
      local wait=$((attempt * 10))
      echo "  $tree_char ⚠️  $label (attempt $attempt failed, retrying in ${wait}s...)"
      echo "         Error: $err_output"
      sleep "$wait"
    fi
  done

  echo "  $tree_char ❌ $label (failed after $max_retries attempts)"
  echo "         Error: $err_output"
  DEPLOY_FAILED=$((DEPLOY_FAILED + 1))
  DEPLOY_LOG="${DEPLOY_LOG}\n  ❌ Failed   $label"
  exit 1
}

# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------
main() {
  print_banner "$PROJECT_NAME" "$TASK_FLOW" "Deploy to Fabric"

  # ---------------------------------------------------------------------------
  # Preflight: CLI only (auth comes after config)
  # ---------------------------------------------------------------------------
  echo "  Checking prerequisites..."
  if ! command -v fab &> /dev/null; then
    echo "  ❌ Fabric CLI (fab) not found."
    echo "     Install with: pip install ms-fabric-cli"
    exit 1
  fi
  echo "  ── ✅ Fabric CLI found"
  echo ""

  # ---------------------------------------------------------------------------
  # Configuration — collect ALL inputs before authenticating
  # ---------------------------------------------------------------------------
  echo "┌──────────────────────────────────────────────────────────────────┐"
  echo "│  CONFIGURATION                                                   │"
  echo "│  Fill in the values below or set as environment variables.       │"
  echo "└──────────────────────────────────────────────────────────────────┘"
  echo ""

  FABRIC_WORKSPACE_NAME=$(prompt_value "FABRIC_WORKSPACE_NAME" "Workspace name" "agent-assist-telco-dev")
  FABRIC_CAPACITY_ID=$(prompt_value "FABRIC_CAPACITY_ID" "Fabric capacity ID (GUID from portal → Capacities)")

  # Connection to source database
  SOURCE_CONNECTION_STRING=$(prompt_value "SOURCE_CONNECTION_STRING" "Source database connection string (e.g., SQL Server, PostgreSQL — used by Copy Job)" "" "optional")
  # Azure Event Hub namespace for streaming
  EVENT_HUB_NAMESPACE=$(prompt_value "EVENT_HUB_NAMESPACE" "Event Hub namespace (Azure Event Hubs that streams events into Fabric)" "" "optional")
  # Consumer group controls which reader offset Eventstream uses
  EVENT_HUB_CONSUMER_GROUP=$(prompt_value "EVENT_HUB_CONSUMER_GROUP" "Event Hub consumer group (isolates this pipeline's read position — use $Default if unsure)" "$Default")

  echo ""
  echo "┌──────────────────────────────────────────────────────────────────┐"
  echo "│  DEPLOYMENT PLAN                                                 │"
  printf "│%-66s│\n" "  Task flow: $TASK_FLOW  |  Items: 16  |  Waves: 7"
  echo "└──────────────────────────────────────────────────────────────────┘"
  echo ""

  echo "  Wave 1 — Foundation + Compute"
  echo "  ├── ☐ Lakehouse: call-transcripts-lakehouse"
  echo "  ├── ☐ Warehouse: call-analytics-warehouse"
  echo "  ├── ☐ Eventhouse: call-events-eventhouse"
  echo "  └── ☐ Environment: spark-env"
  echo ""
  echo "  Wave 2 — Ingestion"
  echo "  ├── ☐ Eventstream: call-stream-eventstream"
  echo "  └── ☐ Data Pipeline: crm-sync-pipeline"
  echo ""
  echo "  Wave 3 — Processing"
  echo "  ├── ☐ Notebook: transcript-etl-notebook"
  echo "  └── ☐ KQL Queryset: call-insights-kql"
  echo ""
  echo "  Wave 4 — Serving"
  echo "  ├── ☐ Semantic Model: call-analytics-model"
  echo "  └── ☐ [MANUAL] Real-Time Dashboard: call-ops-rt-dash"
  echo ""
  echo "  Wave 5 — Visualization"
  echo "  ├── ☐ Report: call-analytics-report"
  echo "  └── ☐ [MANUAL] Activator: call-alert-activator"
  echo ""
  echo "  Wave 6 — ML"
  echo "  ├── ☐ ML Experiment: transcript-ml-experiment"
  echo "  ├── ☐ ML Model: transcript-ml-model"
  echo "  └── ☐ Notebook: ml-scoring-notebook"
  echo ""

  echo ""
  read -rp "  ? Proceed with deployment? [Y/n]: " confirm
  confirm="${confirm:-Y}"
  if [[ ! "$confirm" =~ ^[Yy] ]]; then
    echo "  Deployment cancelled."
    exit 0
  fi

  # ---------------------------------------------------------------------------
  # Authenticate — runs after config so user isn't blocked before providing inputs
  # ---------------------------------------------------------------------------
  echo ""
  echo "  Authenticating..."
  if fab auth status 2>/dev/null; then
    echo "  ── ✅ Already authenticated"
  else
    echo "  ── Opening Fabric login (browser)..."
    fab auth login
    if fab auth status 2>/dev/null; then
      echo "  ── ✅ Authentication successful"
    else
      echo "  ── ❌ Authentication failed."
      echo ""
      echo "     Retry manually with one of:"
      echo "     Interactive:        fab auth login"
      echo "     Service principal:  fab auth login -u <client_id> -p <client_secret> --tenant <tenant_id>"
      echo "     Managed identity:   fab auth login --identity"
      exit 1
    fi
  fi

  # ---------------------------------------------------------------------------
  # Workspace
  # ---------------------------------------------------------------------------
  echo ""
  if fab exists "$FABRIC_WORKSPACE_NAME.Workspace" 2>/dev/null; then
    echo "  ── ✅ Workspace already exists: $FABRIC_WORKSPACE_NAME"
  else
    echo "  Creating workspace..."
    fab_mkdir "$FABRIC_WORKSPACE_NAME.Workspace" "Workspace: $FABRIC_WORKSPACE_NAME" "──"
  fi

  # Assign capacity to workspace
  if [[ -n "$FABRIC_CAPACITY_ID" ]]; then
    echo "  ── Assigning capacity..."
    if fab set "$FABRIC_WORKSPACE_NAME.Workspace" -q capacityId -i "$FABRIC_CAPACITY_ID" 2>/dev/null; then
      echo "  ── ✅ Capacity assigned"
    else
      echo "  ── ⚠️  Could not assign capacity — verify ID in portal (Admin → Capacities)"
    fi
  fi

  # ---------------------------------------------------------------------------
  # Wave Deployment
  # ---------------------------------------------------------------------------
  # ─────────────────────────────────────────────────────────────────
  # Wave 1 — Foundation + Compute
  # ─────────────────────────────────────────────────────────────────
  echo ""
  echo "  Wave 1 — Foundation + Compute"
  fab_mkdir "$FABRIC_WORKSPACE_NAME.Workspace/call-transcripts-lakehouse.Lakehouse" "Lakehouse: call-transcripts-lakehouse" "├──" "-P" "enableSchemas=true"
  fab_mkdir "$FABRIC_WORKSPACE_NAME.Workspace/call-analytics-warehouse.Warehouse" "Warehouse: call-analytics-warehouse" "├──"
  fab_mkdir "$FABRIC_WORKSPACE_NAME.Workspace/call-events-eventhouse.Eventhouse" "Eventhouse: call-events-eventhouse" "├──"
  fab_mkdir "$FABRIC_WORKSPACE_NAME.Workspace/spark-env.Environment" "Environment: spark-env" "└──"

  echo "  ⏳ Waiting for Environment publish (may take 20+ min)..."
  max_wait=1800; elapsed=0
  while [ $elapsed -lt $max_wait ]; do
    sleep 30; elapsed=$((elapsed + 30))
    env_status=$(fab get "$FABRIC_WORKSPACE_NAME.Workspace/spark-env.Environment" -q properties.publishStatus 2>&1)
    echo "    ⏱  $((elapsed / 60))m elapsed — status: $env_status"
    [ "$env_status" = "Published" ] && break
  done
  if [ "$env_status" != "Published" ]; then
    echo "  ⚠️  Environment publish timed out — notebooks may fail until publish completes"
  else
    echo "  ── ✅ Environment published"
  fi

  EVENTHOUSE_ID=$(fab get "$FABRIC_WORKSPACE_NAME.Workspace/call-events-eventhouse.Eventhouse" -q id 2>&1 | tr -d "[:space:]")
  echo "  ── ℹ️  Captured Eventhouse ID: $EVENTHOUSE_ID"

  # ─────────────────────────────────────────────────────────────────
  # Wave 2 — Ingestion
  # ─────────────────────────────────────────────────────────────────
  echo ""
  echo "  Wave 2 — Ingestion"
  fab_mkdir "$FABRIC_WORKSPACE_NAME.Workspace/call-stream-eventstream.Eventstream" "Eventstream: call-stream-eventstream" "├──"
  fab_mkdir "$FABRIC_WORKSPACE_NAME.Workspace/crm-sync-pipeline.DataPipeline" "Data Pipeline: crm-sync-pipeline" "└──"

  # ─────────────────────────────────────────────────────────────────
  # Wave 3 — Processing
  # ─────────────────────────────────────────────────────────────────
  echo ""
  echo "  Wave 3 — Processing"
  fab_mkdir "$FABRIC_WORKSPACE_NAME.Workspace/transcript-etl-notebook.Notebook" "Notebook: transcript-etl-notebook" "├──"
  fab_mkdir "$FABRIC_WORKSPACE_NAME.Workspace/call-insights-kql.KQLQueryset" "KQL Queryset: call-insights-kql" "└──"

  # Bind transcript-etl-notebook to dependencies
  lh_id=$(fab get "$FABRIC_WORKSPACE_NAME.Workspace/call-transcripts-lakehouse.Lakehouse" -q id 2>&1 | tr -d "[:space:]")
  fab set "$FABRIC_WORKSPACE_NAME.Workspace/transcript-etl-notebook.Notebook" -q lakehouse -i "$lh_id" 2>&1 | cat > /dev/null
  echo "  ── ✅ transcript-etl-notebook bound to lakehouse call-transcripts-lakehouse"
  env_id=$(fab get "$FABRIC_WORKSPACE_NAME.Workspace/spark-env.Environment" -q id 2>&1 | tr -d "[:space:]")
  fab set "$FABRIC_WORKSPACE_NAME.Workspace/transcript-etl-notebook.Notebook" -q environment -i "$env_id" 2>&1 | cat > /dev/null
  echo "  ── ✅ transcript-etl-notebook bound to environment spark-env"

  # ─────────────────────────────────────────────────────────────────
  # Wave 4 — Serving
  # ─────────────────────────────────────────────────────────────────
  echo ""
  echo "  Wave 4 — Serving"
  fab_mkdir "$FABRIC_WORKSPACE_NAME.Workspace/call-analytics-model.SemanticModel" "Semantic Model: call-analytics-model" "├──"
  echo "  └── ⏭️  [MANUAL] Real-Time Dashboard: create via Fabric Portal"

  SEMANTIC_MODEL_ID=$(fab get "$FABRIC_WORKSPACE_NAME.Workspace/call-analytics-model.SemanticModel" -q id 2>&1 | tr -d "[:space:]")
  echo "  ── ℹ️  Captured SemanticModel ID: $SEMANTIC_MODEL_ID"

  # ─────────────────────────────────────────────────────────────────
  # Wave 5 — Visualization
  # ─────────────────────────────────────────────────────────────────
  echo ""
  echo "  Wave 5 — Visualization"
  fab_mkdir "$FABRIC_WORKSPACE_NAME.Workspace/call-analytics-report.Report" "Report: call-analytics-report" "├──" "-P" "semanticModelId=$SEMANTIC_MODEL_ID"
  echo "  └── ⏭️  [MANUAL] Activator: create via Fabric Portal"

  # ─────────────────────────────────────────────────────────────────
  # Wave 6 — ML
  # ─────────────────────────────────────────────────────────────────
  echo ""
  echo "  Wave 6 — ML"
  fab_mkdir "$FABRIC_WORKSPACE_NAME.Workspace/transcript-ml-experiment.MLExperiment" "ML Experiment: transcript-ml-experiment" "├──"
  fab_mkdir "$FABRIC_WORKSPACE_NAME.Workspace/transcript-ml-model.MLModel" "ML Model: transcript-ml-model" "├──"
  fab_mkdir "$FABRIC_WORKSPACE_NAME.Workspace/ml-scoring-notebook.Notebook" "Notebook: ml-scoring-notebook" "└──"

  # Bind ml-scoring-notebook to dependencies
  env_id=$(fab get "$FABRIC_WORKSPACE_NAME.Workspace/spark-env.Environment" -q id 2>&1 | tr -d "[:space:]")
  fab set "$FABRIC_WORKSPACE_NAME.Workspace/ml-scoring-notebook.Notebook" -q environment -i "$env_id" 2>&1 | cat > /dev/null
  echo "  ── ✅ ml-scoring-notebook bound to environment spark-env"


  echo ""
  echo "┌──────────────────────────────────────────────────────────────────┐"
  echo "│  DEPLOYMENT SUMMARY                                              │"
  echo "└──────────────────────────────────────────────────────────────────┘"
  echo ""
  printf "%b\n" "$DEPLOY_LOG"
  echo ""
  echo "  Created: $DEPLOY_CREATED  |  Already existed: $DEPLOY_EXISTS  |  Failed: $DEPLOY_FAILED"

  # ---------------------------------------------------------------------------
  # Post-Deployment Metadata
  # ---------------------------------------------------------------------------
  echo ""
  echo "┌──────────────────────────────────────────────────────────────────┐"
  echo "│  POST-DEPLOYMENT METADATA                                       │"
  echo "└──────────────────────────────────────────────────────────────────┘"
  echo ""

  # Workspace ID
  local ws_json
  ws_json=$(fab get "$FABRIC_WORKSPACE_NAME.Workspace" --output json 2>/dev/null || echo "{}")
  local workspace_id
  workspace_id=$(echo "$ws_json" | grep -o '"id"\s*:\s*"[^"]*"' | head -1 | sed 's/.*"id"\s*:\s*"\([^"]*\)".*/\1/')
  workspace_id="${workspace_id:-(unavailable)}"
  echo "  Workspace ID:   $workspace_id"

  # Tenant ID
  local auth_json
  auth_json=$(fab auth status --output json 2>/dev/null || echo "{}")
  local tenant_id
  tenant_id=$(echo "$auth_json" | grep -o '"tenantId"\s*:\s*"[^"]*"' | head -1 | sed 's/.*"tenantId"\s*:\s*"\([^"]*\)".*/\1/')
  tenant_id="${tenant_id:-(unavailable)}"
  echo "  Tenant ID:      $tenant_id"

  # Portal URL
  local portal_base="https://app.fabric.microsoft.com/groups/$workspace_id"
  echo "  Workspace URL:  $portal_base"
  echo ""

  # Per-item IDs
  echo "  Item Details:"
  # Re-parse deploy log for item names is not reliable; items were tracked above.
  # Use fab ls to enumerate workspace items.
  local items_json
  items_json=$(fab ls "$FABRIC_WORKSPACE_NAME.Workspace" --output json 2>/dev/null || echo "[]")
  echo "$items_json" | grep -o '"displayName"\s*:\s*"[^"]*"\|"id"\s*:\s*"[^"]*"' | paste - - | while read -r line; do
    local item_name item_id
    item_name=$(echo "$line" | sed 's/.*"displayName"\s*:\s*"\([^"]*\)".*/\1/')
    item_id=$(echo "$line" | sed 's/.*"id"\s*:\s*"\([^"]*\)".*/\1/')
    echo "  ├── $item_name  →  ID: $item_id"
  done
  echo ""
  echo "  ℹ️  Save these IDs — they are required for CI/CD parameterization"
  echo "     and fabric-cicd library configuration."
}

main "$@"
