# =============================================================================
# Fabric Task Flows — Deploy Script (PowerShell)
# Generated by @fabric-engineer
#
# Project:   {{PROJECT_NAME}}
# Task Flow: {{TASK_FLOW}}
# Generated: {{DATE}}
# =============================================================================
$ErrorActionPreference = "Stop"

# ---------------------------------------------------------------------------
# Brand Banner
# ---------------------------------------------------------------------------
function Print-Banner {
  param(
    [string]$ProjectName = "Project",
    [string]$TaskFlow = "unknown",
    [string]$Mode = "Deploy"
  )

  Write-Host ""
  Write-Host "╔══════════════════════════════════════════════════════════════════╗"
  Write-Host "║                                                                  ║"
  Write-Host "║        /@@@@@@@@@@@@@@/                                          ║"
  Write-Host "║       /@@@@@@@@@@@@@@/  ╔════════════════════════════════════╗   ║"
  Write-Host "║      /@@@@/             ║                                    ║   ║"
  Write-Host "║     /@@@@@@@@@@@@@/     ║  F A B R I C   T A S K   F L O W S ║   ║"
  Write-Host "║    /@@@@/               ║  ──────────────────────────────── ║   ║"
  Write-Host "║   /@@@@/                ║  Deploy Microsoft Fabric           ║   ║"
  Write-Host "║  /@@@@/                 ║  architectures to production       ║   ║"
  Write-Host "║                         ╚════════════════════════════════════╝   ║"
  Write-Host "║                                                                  ║"
  Write-Host ("║   Project:   {0,-49} ║" -f $ProjectName)
  Write-Host ("║   Task Flow: {0,-49} ║" -f $TaskFlow)
  Write-Host ("║   Mode:      {0,-49} ║" -f $Mode)
  Write-Host "║                                                                  ║"
  Write-Host "╚══════════════════════════════════════════════════════════════════╝"
  Write-Host ""
}

# ---------------------------------------------------------------------------
# Configuration
# ---------------------------------------------------------------------------
$ProjectName = "{{PROJECT_NAME}}"
$TaskFlow = "{{TASK_FLOW}}"

# ---------------------------------------------------------------------------
# Interactive prompts (with env var fallbacks)
# ---------------------------------------------------------------------------
function Prompt-Value {
  param(
    [string]$EnvVarName,
    [string]$PromptText,
    [string]$DefaultValue = ""
  )

  $envValue = [System.Environment]::GetEnvironmentVariable($EnvVarName)
  if ($envValue) { return $envValue }

  if ($DefaultValue) {
    $input = Read-Host "  ? $PromptText [$DefaultValue]"
    if ([string]::IsNullOrWhiteSpace($input)) { return $DefaultValue }
    return $input
  } else {
    return Read-Host "  ? $PromptText"
  }
}

function Prompt-Choice {
  param(
    [string]$PromptText,
    [string[]]$Options
  )

  Write-Host "  ? $PromptText"
  for ($i = 0; $i -lt $Options.Count; $i++) {
    if ($i -eq 0) {
      Write-Host "    > $($Options[$i])"
    } else {
      Write-Host "      $($Options[$i])"
    }
  }

  $choice = Read-Host "  Enter choice (1-$($Options.Count)) [1]"
  if ([string]::IsNullOrWhiteSpace($choice)) { $choice = "1" }
  return $Options[[int]$choice - 1]
}

# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------
function Main {
  Print-Banner -ProjectName $ProjectName -TaskFlow $TaskFlow -Mode "Deploy to Fabric"

  Write-Host "┌─────────────────────────────────────────────────────────────┐"
  Write-Host "│  CONFIGURATION                                              │"
  Write-Host "│  Fill in the values below or set as environment variables.  │"
  Write-Host "└─────────────────────────────────────────────────────────────┘"
  Write-Host ""

  $WorkspaceName = Prompt-Value -EnvVarName "FABRIC_WORKSPACE_NAME" -PromptText "Workspace name" -DefaultValue "{{PROJECT_SLUG}}-dev"
  $CapacityId = Prompt-Value -EnvVarName "FABRIC_CAPACITY_ID" -PromptText "Fabric Capacity ID"
  $TenantId = Prompt-Value -EnvVarName "FABRIC_TENANT_ID" -PromptText "Azure AD Tenant ID"
  $Environment = Prompt-Value -EnvVarName "FABRIC_ENVIRONMENT" -PromptText "Target environment" -DefaultValue "dev"
  $AuthMethod = Prompt-Choice -PromptText "Authentication method" -Options @("Interactive login (fab auth login)", "Service principal", "Managed identity")

  # {{TASK_FLOW_SPECIFIC_PROMPTS}}
  # Agent: Insert task-flow-specific prompts here

  Write-Host ""
  Write-Host "┌─────────────────────────────────────────────────────────────┐"
  Write-Host "│  DEPLOYMENT PLAN                                            │"
  Write-Host "│  Task flow: $TaskFlow  |  Items: {{ITEM_COUNT}}  |  Waves: {{WAVE_COUNT}}           │"
  Write-Host "└─────────────────────────────────────────────────────────────┘"
  Write-Host ""

  # {{DEPLOYMENT_PLAN_PREVIEW}}
  # Agent: Insert wave-by-wave preview here

  Write-Host ""
  $confirm = Read-Host "  ? Proceed with deployment? [Y/n]"
  if ($confirm -and $confirm -notmatch "^[Yy]") {
    Write-Host "  Deployment cancelled."
    return
  }

  # ---------------------------------------------------------------------------
  # Authentication
  # ---------------------------------------------------------------------------
  Write-Host ""
  Write-Host "  Authenticating..."
  switch -Wildcard ($AuthMethod) {
    "Interactive*" { fab auth login }
    "Service*" {
      $ClientId = Prompt-Value -EnvVarName "SPN_CLIENT_ID" -PromptText "Service Principal Client ID"
      $ClientSecret = Prompt-Value -EnvVarName "SPN_CLIENT_SECRET" -PromptText "Service Principal Client Secret"
      fab auth login -u $ClientId -p $ClientSecret --tenant $TenantId
    }
    "Managed*" { fab auth login --identity }
  }
  Write-Host "  ✅ Authenticated"

  # ---------------------------------------------------------------------------
  # Wave Deployment
  # ---------------------------------------------------------------------------
  # {{WAVE_DEPLOYMENT}}
  # Agent: Insert fab mkdir commands grouped by wave

  Write-Host ""
  Write-Host "┌─────────────────────────────────────────────────────────────┐"
  Write-Host "│  DEPLOYMENT COMPLETE                                        │"
  Write-Host "│  All items deployed successfully.                           │"
  Write-Host "└─────────────────────────────────────────────────────────────┘"
}

Main
