#!/usr/bin/env bash
# =============================================================================
# Fabric Task Flows — Deploy Script
# Generated by @fabric-engineer
#
# Project:   {{PROJECT_NAME}}
# Task Flow: {{TASK_FLOW}}
# Generated: {{DATE}}
# =============================================================================
set -euo pipefail

# ---------------------------------------------------------------------------
# Brand Banner
# ---------------------------------------------------------------------------
print_banner() {
  local project_name="${1:-Project}"
  local task_flow="${2:-unknown}"
  local mode="${3:-Deploy}"

  echo ""
  echo "╔═════════════════════════════════════════════╗"
  echo "║                                             ║"
  echo "║   ┌──────────────────────────────────────┐  ║"
  echo "║   │ F A B R I C   T A S K   F L O W S    │  ║"
  echo "║   │ ──────────────────────────────────── │  ║"
  echo "║   │ Deploy Microsoft Fabric              │  ║"
  echo "║   │ architectures to production          │  ║"
  echo "║   └──────────────────────────────────────┘  ║"
  echo "║                                             ║"
  printf "║  Project:   %-45s ║\n" "$project_name"
  printf "║  Task Flow: %-45s ║\n" "$task_flow"
  printf "║  Mode:      %-45s ║\n" "$mode"
  echo "║                                             ║"
  echo "╚═════════════════════════════════════════════╝"
  echo ""
}

# ---------------------------------------------------------------------------
# Configuration — fill these or set as environment variables
# ---------------------------------------------------------------------------
PROJECT_NAME="{{PROJECT_NAME}}"
TASK_FLOW="{{TASK_FLOW}}"

# ---------------------------------------------------------------------------
# Interactive prompts (with env var fallbacks)
# ---------------------------------------------------------------------------
prompt_value() {
  local var_name="$1"
  local prompt_text="$2"
  local default_value="${3:-}"
  local optional="${4:-}"
  local env_value="${!var_name:-}"

  if [[ -n "$env_value" ]]; then
    echo "$env_value"
    return
  fi

  if [[ -n "$default_value" ]]; then
    read -rp "  ? $prompt_text (Enter = $default_value, or type to rename): " input
    echo "${input:-$default_value}"
  elif [[ "$optional" == "optional" ]]; then
    read -rp "  ? $prompt_text (optional, Enter to skip): " input
    echo "$input"
  else
    read -rp "  ? $prompt_text: " input
    echo "$input"
  fi
}

DEPLOY_CREATED=0
DEPLOY_EXISTS=0
DEPLOY_FAILED=0
DEPLOY_LOG=""

fab_mkdir() {
  local path="$1"
  local label="$2"
  local tree_char="${3:-├──}"
  shift 3 2>/dev/null || true
  local extra_args=("$@")
  local max_retries=3
  local err_output

  # Idempotency: skip if item already exists
  # fab exists outputs '* true' or '* false' (exit code is always 0)
  if fab exists "$path" 2>/dev/null | grep -q "\* true"; then
    echo "  $tree_char ✅ $label (already exists)"
    DEPLOY_EXISTS=$((DEPLOY_EXISTS + 1))
    DEPLOY_LOG="${DEPLOY_LOG}\n  ✅ Exists   $label"
    return
  fi

  # Retry with backoff for transient failures
  for attempt in $(seq 1 $max_retries); do
    err_output=$(fab mkdir "$path" ${extra_args[*]} 2>&1)
    if [ $? -eq 0 ]; then
      echo "  $tree_char ✅ $label"
      DEPLOY_CREATED=$((DEPLOY_CREATED + 1))
      DEPLOY_LOG="${DEPLOY_LOG}\n  ✅ Created  $label"
      return
    fi
    if [ "$attempt" -lt "$max_retries" ]; then
      local wait=$((attempt * 10))
      echo "  $tree_char ⚠️  $label (attempt $attempt failed, retrying in ${wait}s...)"
      echo "         Error: $err_output"
      sleep "$wait"
    fi
  done

  echo "  $tree_char ❌ $label (failed after $max_retries attempts)"
  echo "         Error: $err_output"
  DEPLOY_FAILED=$((DEPLOY_FAILED + 1))
  DEPLOY_LOG="${DEPLOY_LOG}\n  ❌ Failed   $label"
  exit 1
}

# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------
main() {
  print_banner "$PROJECT_NAME" "$TASK_FLOW" "Deploy to Fabric"

  # ---------------------------------------------------------------------------
  # Preflight: CLI only (auth comes after config)
  # ---------------------------------------------------------------------------
  echo "  Checking prerequisites..."
  if ! command -v fab &> /dev/null; then
    echo "  ❌ Fabric CLI (fab) not found."
    echo "     Install with: pip install ms-fabric-cli"
    exit 1
  fi
  echo "  ── ✅ Fabric CLI found"
  echo ""

  # ---------------------------------------------------------------------------
  # Configuration — collect ALL inputs before authenticating
  # ---------------------------------------------------------------------------
  echo "┌──────────────────────────────────────────────────────────────────┐"
  echo "│  CONFIGURATION                                                   │"
  echo "│  Fill in the values below or set as environment variables.       │"
  echo "└──────────────────────────────────────────────────────────────────┘"
  echo ""

  FABRIC_WORKSPACE_NAME=$(prompt_value "FABRIC_WORKSPACE_NAME" "Workspace name" "{{PROJECT_SLUG}}-dev")
  FABRIC_CAPACITY_NAME=$(prompt_value "FABRIC_CAPACITY_NAME" "Fabric capacity name (from Admin Portal → Capacities)" "" "optional")

  # {{TASK_FLOW_SPECIFIC_PROMPTS}}
  # Agent: Insert task-flow-specific prompts here (Event Hub, SQL connections, etc.)

  echo ""
  echo "┌──────────────────────────────────────────────────────────────────┐"
  echo "│  DEPLOYMENT PLAN                                                 │"
  printf "│%-66s│\n" "  Task flow: $TASK_FLOW  |  Items: {{ITEM_COUNT}}  |  Waves: {{WAVE_COUNT}}"
  echo "└──────────────────────────────────────────────────────────────────┘"
  echo ""

  # {{DEPLOYMENT_PLAN_PREVIEW}}
  # Agent: Insert wave-by-wave preview here, e.g.:
  #   echo "  Wave 1 ─ Foundation"
  #   echo "  ├── ☐ Workspace: $FABRIC_WORKSPACE_NAME"
  #   echo "  ├── ☐ Lakehouse: {{item-name}}"
  #   echo "  └── ☐ Lakehouse: {{item-name}}"

  echo ""
  read -rp "  ? Proceed with deployment? [Y/n]: " confirm
  confirm="${confirm:-Y}"
  if [[ ! "$confirm" =~ ^[Yy] ]]; then
    echo "  Deployment cancelled."
    exit 0
  fi

  # ---------------------------------------------------------------------------
  # Authenticate — verify auth; if not logged in, auto-login via browser
  # ---------------------------------------------------------------------------
  echo ""
  echo "  Checking authentication..."
  local auth_out
  auth_out=$(fab auth status 2>&1)
  if echo "$auth_out" | grep -qi "Not logged in"; then
    echo "  ── Not authenticated — launching browser login..."
    fab auth login 2>/dev/null
    auth_out=$(fab auth status 2>&1)
    if echo "$auth_out" | grep -qi "Not logged in"; then
      echo "  ── ❌ Authentication failed."
      echo ""
      echo "     Run manually:  fab auth login"
      echo "     Then re-run this script."
      exit 1
    fi
  fi
  echo "  ── ✅ Authenticated"

  # ---------------------------------------------------------------------------
  # Workspace
  # ---------------------------------------------------------------------------
  echo ""
  if fab exists "$FABRIC_WORKSPACE_NAME.Workspace" 2>/dev/null | grep -q "\* true"; then
    echo "  ── ✅ Workspace already exists: $FABRIC_WORKSPACE_NAME"
  else
    echo "  Creating workspace..."
    fab_mkdir "$FABRIC_WORKSPACE_NAME.Workspace" "Workspace: $FABRIC_WORKSPACE_NAME" "──"
  fi

  # Assign capacity to workspace
  if [[ -n "$FABRIC_CAPACITY_NAME" ]]; then
    echo "  ── Assigning capacity..."
    if fab assign ".capacities/$FABRIC_CAPACITY_NAME.Capacity" -W "$FABRIC_WORKSPACE_NAME.Workspace" 2>/dev/null; then
      echo "  ── ✅ Capacity assigned: $FABRIC_CAPACITY_NAME"
    else
      echo "  ── ⚠️  Could not assign capacity '$FABRIC_CAPACITY_NAME'"
      echo "         Run 'fab ls .capacities' to list available capacities"
    fi
  fi

  # ---------------------------------------------------------------------------
  # Wave Deployment
  # ---------------------------------------------------------------------------
  # {{WAVE_DEPLOYMENT}}
  # Agent: Insert fab mkdir commands grouped by wave, e.g.:
  #
  #   echo ""
  #   echo "  Wave 1 ─ Foundation"
  #   fab mkdir "$FABRIC_WORKSPACE_NAME.Workspace"
  #   echo "  ├── ✅ Workspace: $FABRIC_WORKSPACE_NAME"
  #   fab mkdir "$FABRIC_WORKSPACE_NAME.Workspace/{{item-name}}.Lakehouse" -P enableSchemas=true
  #   echo "  ├── ✅ Lakehouse: {{item-name}}"

  echo ""
  echo "┌──────────────────────────────────────────────────────────────────┐"
  echo "│  DEPLOYMENT SUMMARY                                              │"
  echo "└──────────────────────────────────────────────────────────────────┘"
  echo ""
  printf "%b\n" "$DEPLOY_LOG"
  echo ""
  echo "  Created: $DEPLOY_CREATED  |  Already existed: $DEPLOY_EXISTS  |  Failed: $DEPLOY_FAILED"

  # ---------------------------------------------------------------------------
  # Post-Deployment Metadata
  # ---------------------------------------------------------------------------
  echo ""
  echo "┌──────────────────────────────────────────────────────────────────┐"
  echo "│  POST-DEPLOYMENT METADATA                                       │"
  echo "└──────────────────────────────────────────────────────────────────┘"
  echo ""

  # Workspace ID
  local ws_json
  ws_json=$(fab get "$FABRIC_WORKSPACE_NAME.Workspace" -q . 2>/dev/null || echo "{}")
  local workspace_id
  workspace_id=$(echo "$ws_json" | grep -o '"id"\s*:\s*"[^"]*"' | head -1 | sed 's/.*"id"\s*:\s*"\([^"]*\)".*/\1/')
  workspace_id="${workspace_id:-(unavailable)}"
  echo "  Workspace ID:   $workspace_id"

  # Tenant ID (parse from auth status text)
  local auth_text
  auth_text=$(fab auth status 2>/dev/null || echo "")
  local tenant_id
  tenant_id=$(echo "$auth_text" | grep -o 'Tenant ID:\s*\S*' | sed 's/Tenant ID:\s*//')
  tenant_id="${tenant_id:-(unavailable)}"
  echo "  Tenant ID:      $tenant_id"

  # Portal URL
  local portal_base="https://app.fabric.microsoft.com/groups/$workspace_id"
  echo "  Workspace URL:  $portal_base"
  echo ""

  # Per-item IDs
  echo "  Item Details:"
  local items_text
  items_text=$(fab ls "$FABRIC_WORKSPACE_NAME.Workspace" -l 2>/dev/null || echo "")
  echo "$items_text"
  echo ""
  echo "  ℹ️  Save these IDs — they are required for CI/CD parameterization"
  echo "     and fabric-cicd library configuration."
}

main "$@"
