#!/usr/bin/env bash
# =============================================================================
# Fabric Task Flows — Deploy Script
# Generated by @fabric-engineer
#
# Project:   {{PROJECT_NAME}}
# Task Flow: {{TASK_FLOW}}
# Generated: {{DATE}}
# =============================================================================
set -euo pipefail

# ---------------------------------------------------------------------------
# Brand Banner
# ---------------------------------------------------------------------------
print_banner() {
  local project_name="${1:-Project}"
  local task_flow="${2:-unknown}"
  local mode="${3:-Deploy}"

  echo ""
  echo "╔══════════════════════════════════════════════════════════════════╗"
  echo "║                                                                  ║"
  echo "║        /@@@@@@@@@@@@@@/                                          ║"
  echo "║       /@@@@@@@@@@@@@@/  ╔════════════════════════════════════╗   ║"
  echo "║      /@@@@/             ║                                    ║   ║"
  echo "║     /@@@@@@@@@@@@@/     ║  F A B R I C   T A S K   F L O W S ║   ║"
  echo "║    /@@@@/               ║  ──────────────────────────────── ║   ║"
  echo "║   /@@@@/                ║  Deploy Microsoft Fabric           ║   ║"
  echo "║  /@@@@/                 ║  architectures to production       ║   ║"
  echo "║                         ╚════════════════════════════════════╝   ║"
  echo "║                                                                  ║"
  printf "║   Project:   %-49s ║\n" "$project_name"
  printf "║   Task Flow: %-49s ║\n" "$task_flow"
  printf "║   Mode:      %-49s ║\n" "$mode"
  echo "║                                                                  ║"
  echo "╚══════════════════════════════════════════════════════════════════╝"
  echo ""
}

# ---------------------------------------------------------------------------
# Configuration — fill these or set as environment variables
# ---------------------------------------------------------------------------
PROJECT_NAME="{{PROJECT_NAME}}"
TASK_FLOW="{{TASK_FLOW}}"

# ---------------------------------------------------------------------------
# Interactive prompts (with env var fallbacks)
# ---------------------------------------------------------------------------
prompt_value() {
  local var_name="$1"
  local prompt_text="$2"
  local default_value="${3:-}"
  local env_value="${!var_name:-}"

  if [[ -n "$env_value" ]]; then
    echo "$env_value"
    return
  fi

  if [[ -n "$default_value" ]]; then
    read -rp "  ? $prompt_text [$default_value]: " input
    echo "${input:-$default_value}"
  else
    read -rp "  ? $prompt_text: " input
    echo "$input"
  fi
}

prompt_choice() {
  local prompt_text="$1"
  shift
  local options=("$@")

  echo "  ? $prompt_text"
  for i in "${!options[@]}"; do
    if [[ $i -eq 0 ]]; then
      echo "    ❯ ${options[$i]}"
    else
      echo "      ${options[$i]}"
    fi
  done

  local choice
  read -rp "  Enter choice (1-${#options[@]}) [1]: " choice
  choice="${choice:-1}"
  echo "${options[$((choice - 1))]}"
}

# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------
main() {
  print_banner "$PROJECT_NAME" "$TASK_FLOW" "Deploy to Fabric"

  echo "┌─────────────────────────────────────────────────────────────┐"
  echo "│  CONFIGURATION                                              │"
  echo "│  Fill in the values below or set as environment variables.  │"
  echo "└─────────────────────────────────────────────────────────────┘"
  echo ""

  FABRIC_WORKSPACE_NAME=$(prompt_value "FABRIC_WORKSPACE_NAME" "Workspace name" "{{PROJECT_SLUG}}-dev")
  FABRIC_CAPACITY_ID=$(prompt_value "FABRIC_CAPACITY_ID" "Fabric Capacity ID")
  FABRIC_TENANT_ID=$(prompt_value "FABRIC_TENANT_ID" "Azure AD Tenant ID")
  FABRIC_ENVIRONMENT=$(prompt_value "FABRIC_ENVIRONMENT" "Target environment" "dev")
  FABRIC_AUTH_METHOD=$(prompt_choice "Authentication method" "Interactive login (fab auth login)" "Service principal" "Managed identity")

  # {{TASK_FLOW_SPECIFIC_PROMPTS}}
  # Agent: Insert task-flow-specific prompts here (Event Hub, SQL connections, etc.)

  echo ""
  echo "┌─────────────────────────────────────────────────────────────┐"
  echo "│  DEPLOYMENT PLAN                                            │"
  echo "│  Task flow: $TASK_FLOW  |  Items: {{ITEM_COUNT}}  |  Waves: {{WAVE_COUNT}}           │"
  echo "└─────────────────────────────────────────────────────────────┘"
  echo ""

  # {{DEPLOYMENT_PLAN_PREVIEW}}
  # Agent: Insert wave-by-wave preview here, e.g.:
  #   echo "  Wave 1 ─ Foundation"
  #   echo "  ├── ☐ Workspace: $FABRIC_WORKSPACE_NAME"
  #   echo "  ├── ☐ Lakehouse: {{item-name}}"
  #   echo "  └── ☐ Lakehouse: {{item-name}}"

  echo ""
  read -rp "  ? Proceed with deployment? [Y/n]: " confirm
  confirm="${confirm:-Y}"
  if [[ ! "$confirm" =~ ^[Yy] ]]; then
    echo "  Deployment cancelled."
    exit 0
  fi

  # ---------------------------------------------------------------------------
  # Authentication
  # ---------------------------------------------------------------------------
  echo ""
  echo "  Authenticating..."
  case "$FABRIC_AUTH_METHOD" in
    "Interactive login"*) fab auth login ;;
    "Service principal"*)
      SPN_CLIENT_ID=$(prompt_value "SPN_CLIENT_ID" "Service Principal Client ID")
      SPN_CLIENT_SECRET=$(prompt_value "SPN_CLIENT_SECRET" "Service Principal Client Secret")
      fab auth login -u "$SPN_CLIENT_ID" -p "$SPN_CLIENT_SECRET" --tenant "$FABRIC_TENANT_ID"
      ;;
    "Managed identity"*) fab auth login --identity ;;
  esac
  echo "  ✅ Authenticated"

  # ---------------------------------------------------------------------------
  # Wave Deployment
  # ---------------------------------------------------------------------------
  # {{WAVE_DEPLOYMENT}}
  # Agent: Insert fab mkdir commands grouped by wave, e.g.:
  #
  #   echo ""
  #   echo "  Wave 1 ─ Foundation"
  #   fab mkdir "$FABRIC_WORKSPACE_NAME.Workspace"
  #   echo "  ├── ✅ Workspace: $FABRIC_WORKSPACE_NAME"
  #   fab mkdir "$FABRIC_WORKSPACE_NAME.Workspace/{{item-name}}.Lakehouse" -P enableSchemas=true
  #   echo "  ├── ✅ Lakehouse: {{item-name}}"

  echo ""
  echo "┌─────────────────────────────────────────────────────────────┐"
  echo "│  DEPLOYMENT COMPLETE                                        │"
  echo "│  All items deployed successfully.                           │"
  echo "└─────────────────────────────────────────────────────────────┘"
}

main "$@"
