# =============================================================================
# Fabric Task Flows — Deploy Script (PowerShell)
# Generated by @fabric-engineer
#
# Project:   {{PROJECT_NAME}}
# Task Flow: {{TASK_FLOW}}
# Generated: {{DATE}}
# =============================================================================
$ErrorActionPreference = "Stop"

# ---------------------------------------------------------------------------
# Brand Banner
# ---------------------------------------------------------------------------
function Print-Banner {
  param(
    [string]$ProjectName = "Project",
    [string]$TaskFlow = "unknown",
    [string]$Mode = "Deploy"
  )

  Write-Host ""
  Write-Host "╔══════════════════════════════════════════════════════════════════╗"
  Write-Host "║                                                                  ║"
  Write-Host "║        /@@@@@@@@@@@@/  ┌──────────────────────────────────────┐  ║"
  Write-Host "║       /@@@@@@@@@@@@/   │ F A B R I C   T A S K   F L O W S    │  ║"  
  Write-Host "║      /@@@@@@@@@/       │ ──────────────────────────────────── │  ║"
  Write-Host "║     /@@@@@@/           │ Deploy Microsoft Fabric              │  ║"
  Write-Host "║    /@@@@@@/            │ architectures to production          │  ║"
  Write-Host "║                        └──────────────────────────────────────┘  ║"
  Write-Host "║                                                                  ║"
  Write-Host ("║  Project:   {0,-52} ║" -f $ProjectName)
  Write-Host ("║  Task Flow: {0,-52} ║" -f $TaskFlow)
  Write-Host ("║  Mode:      {0,-52} ║" -f $Mode)
  Write-Host "║                                                                  ║"
  Write-Host "╚══════════════════════════════════════════════════════════════════╝"
  Write-Host ""
}

# ---------------------------------------------------------------------------
# Configuration
# ---------------------------------------------------------------------------
$ProjectName = "{{PROJECT_NAME}}"
$TaskFlow = "{{TASK_FLOW}}"

# ---------------------------------------------------------------------------
# Interactive prompts (with env var fallbacks)
# ---------------------------------------------------------------------------
function Prompt-Value {
  param(
    [string]$EnvVarName,
    [string]$PromptText,
    [string]$DefaultValue = "",
    [switch]$Optional
  )

  $envValue = [System.Environment]::GetEnvironmentVariable($EnvVarName)
  if ($envValue) { return $envValue }

  if ($DefaultValue) {
    $input = Read-Host "  ? $PromptText (Enter = $DefaultValue, or type to rename)"
    if ([string]::IsNullOrWhiteSpace($input)) { return $DefaultValue }
    return $input
  } elseif ($Optional) {
    $input = Read-Host "  ? $PromptText (optional, Enter to skip)"
    if ([string]::IsNullOrWhiteSpace($input)) { return "" }
    return $input
  } else {
    return Read-Host "  ? $PromptText"
  }
}

function Fab-Mkdir {
  param(
    [string]$Path,
    [string]$Label,
    [string]$TreeChar = "├──",
    [string[]]$ExtraArgs = @(),
    [int]$MaxRetries = 3
  )

  # Idempotency: skip if item already exists
  fab exists "$Path" 2>&1 | Out-Null
  if ($LASTEXITCODE -eq 0) {
    Write-Host "  $TreeChar ✅ $Label (already exists)"
    $script:DeployResults += @{ Label = $Label; Status = "exists" }
    return
  }

  # Retry with backoff for transient failures
  for ($attempt = 1; $attempt -le $MaxRetries; $attempt++) {
    $allArgs = @("mkdir", $Path) + $ExtraArgs
    & fab @allArgs 2>&1 | Out-Null
    if ($LASTEXITCODE -eq 0) {
      Write-Host "  $TreeChar ✅ $Label"
      $script:DeployResults += @{ Label = $Label; Status = "created" }
      return
    }
    if ($attempt -lt $MaxRetries) {
      $wait = $attempt * 10
      Write-Host "  $TreeChar ⚠️  $Label (attempt $attempt failed, retrying in ${wait}s...)"
      Start-Sleep -Seconds $wait
    }
  }

  Write-Host "  $TreeChar ❌ $Label (failed after $MaxRetries attempts)"
  $script:DeployResults += @{ Label = $Label; Status = "failed" }
  throw "Deployment failed: $Label"
}

# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------
function Main {
  Print-Banner -ProjectName $ProjectName -TaskFlow $TaskFlow -Mode "Deploy to Fabric"

  # ---------------------------------------------------------------------------
  # Preflight checks
  # ---------------------------------------------------------------------------
  Write-Host "  Checking prerequisites..."
  $fabCmd = Get-Command fab -ErrorAction SilentlyContinue
  if (-not $fabCmd) {
    Write-Host "  ❌ Fabric CLI (fab) not found."
    Write-Host "     Install with: pip install ms-fabric-cli"
    return
  }
  Write-Host "  ── ✅ Fabric CLI found"
  Write-Host ""

  # Track deployment results
  $script:DeployResults = @()

  Write-Host "┌──────────────────────────────────────────────────────────────────┐"
  Write-Host "│  CONFIGURATION                                                   │"
  Write-Host "│  Fill in the values below or set as environment variables.       │"
  Write-Host "└──────────────────────────────────────────────────────────────────┘"
  Write-Host ""

  $WorkspaceName = Prompt-Value -EnvVarName "FABRIC_WORKSPACE_NAME" -PromptText "Workspace name" -DefaultValue "{{PROJECT_SLUG}}-dev"

  # {{TASK_FLOW_SPECIFIC_PROMPTS}}
  # Agent: Insert task-flow-specific prompts here

  Write-Host ""
  Write-Host "┌──────────────────────────────────────────────────────────────────┐"
  Write-Host "│  DEPLOYMENT PLAN                                                 │"
  Write-Host ("│{0,-66}│" -f "  Task flow: $TaskFlow  |  Items: {{ITEM_COUNT}}  |  Waves: {{WAVE_COUNT}}")
  Write-Host "└──────────────────────────────────────────────────────────────────┘"
  Write-Host ""

  # {{DEPLOYMENT_PLAN_PREVIEW}}
  # Agent: Insert wave-by-wave preview here

  Write-Host ""
  $confirm = Read-Host "  ? Proceed with deployment? [Y/n]"
  if ($confirm -and $confirm -notmatch "^[Yy]") {
    Write-Host "  Deployment cancelled."
    return
  }

  # ---------------------------------------------------------------------------
  # Workspace
  # ---------------------------------------------------------------------------
  Write-Host ""
  fab exists "$WorkspaceName.Workspace" 2>&1 | Out-Null
  if ($LASTEXITCODE -eq 0) {
    Write-Host "  ── ✅ Workspace already exists: $WorkspaceName"
  } else {
    Write-Host "  Creating workspace..."
    Fab-Mkdir -Path "$WorkspaceName.Workspace" -Label "Workspace: $WorkspaceName" -TreeChar "──"
  }

  # ---------------------------------------------------------------------------
  # Wave Deployment
  # ---------------------------------------------------------------------------
  # {{WAVE_DEPLOYMENT}}
  # Agent: Insert fab mkdir commands grouped by wave

  Write-Host ""
  Write-Host "┌──────────────────────────────────────────────────────────────────┐"
  Write-Host "│  DEPLOYMENT SUMMARY                                              │"
  Write-Host "└──────────────────────────────────────────────────────────────────┘"
  Write-Host ""
  $created = ($script:DeployResults | Where-Object { $_.Status -eq "created" }).Count
  $existed = ($script:DeployResults | Where-Object { $_.Status -eq "exists" }).Count
  $failed  = ($script:DeployResults | Where-Object { $_.Status -eq "failed" }).Count
  foreach ($r in $script:DeployResults) {
    $icon = switch ($r.Status) { "created" { "✅ Created" } "exists" { "✅ Exists " } "failed" { "❌ Failed " } default { "⏭️  Skipped" } }
    Write-Host "  $icon  $($r.Label)"
  }
  Write-Host ""
  Write-Host "  Created: $created  |  Already existed: $existed  |  Failed: $failed"

  # ---------------------------------------------------------------------------
  # Post-Deployment Metadata
  # ---------------------------------------------------------------------------
  Write-Host ""
  Write-Host "┌──────────────────────────────────────────────────────────────────┐"
  Write-Host "│  POST-DEPLOYMENT METADATA                                       │"
  Write-Host "└──────────────────────────────────────────────────────────────────┘"
  Write-Host ""

  # Workspace ID
  $wsInfo = fab get "$WorkspaceName.Workspace" --output json 2>$null | ConvertFrom-Json
  $WorkspaceId = if ($wsInfo.id) { $wsInfo.id } else { "(unavailable)" }
  Write-Host "  Workspace ID:   $WorkspaceId"

  # Tenant ID
  $authInfo = fab auth status --output json 2>$null | ConvertFrom-Json
  $TenantId = if ($authInfo.tenantId) { $authInfo.tenantId } else { "(unavailable)" }
  Write-Host "  Tenant ID:      $TenantId"

  # Portal URL
  $portalBase = "https://app.fabric.microsoft.com/groups/$WorkspaceId"
  Write-Host "  Workspace URL:  $portalBase"
  Write-Host ""

  # Per-item IDs
  Write-Host "  Item Details:"
  foreach ($r in $script:DeployResults) {
    if ($r.Status -eq "created" -or $r.Status -eq "exists") {
      $itemName = ($r.Label -split ":\s*", 2)[-1].Trim()
      $itemInfo = fab get "$WorkspaceName.Workspace/$itemName" --output json 2>$null | ConvertFrom-Json
      $itemId = if ($itemInfo.id) { $itemInfo.id } else { "-" }
      Write-Host "  ├── $($r.Label)  →  ID: $itemId"
    }
  }
  Write-Host ""
  Write-Host "  ℹ️  Save these IDs — they are required for CI/CD parameterization"
  Write-Host "     and fabric-cicd library configuration."
}

Main
