# =============================================================================
# Fabric Task Flows — Deploy Script (PowerShell)
# Generated by @fabric-engineer
#
# Project:   {{PROJECT_NAME}}
# Task Flow: {{TASK_FLOW}}
# Generated: {{DATE}}
#
# CLI Reference: fab v0.1.10+ (pip install ms-fabric-cli)
# Verified: exists → "* true"/"* false", get -q ., assign, mkdir
# =============================================================================
$ErrorActionPreference = "Stop"

# ---------------------------------------------------------------------------
# Brand Banner
# ---------------------------------------------------------------------------
function Print-Banner {
  param(
    [string]$ProjectName = "Project",
    [string]$TaskFlow = "unknown",
    [string]$Mode = "Deploy"
  )

  Write-Host ""
  Write-Host "╔══════════════════════════════════════════════════════════════════╗"
  Write-Host "║                                                                  ║"
  Write-Host "║        /@@@@@@@@@@@@/  ┌──────────────────────────────────────┐  ║"
  Write-Host "║       /@@@@@@@@@@@@/   │ F A B R I C   T A S K   F L O W S    │  ║"
  Write-Host "║      /@@@@@@@@@/       │ ──────────────────────────────────── │  ║"
  Write-Host "║     /@@@@@@/           │ Deploy Microsoft Fabric              │  ║"
  Write-Host "║    /@@@@@@/            │ architectures to production          │  ║"
  Write-Host "║                        └──────────────────────────────────────┘  ║"
  Write-Host "║                                                                  ║"
  Write-Host ("║  Project:   {0,-52} ║" -f $ProjectName)
  Write-Host ("║  Task Flow: {0,-52} ║" -f $TaskFlow)
  Write-Host ("║  Mode:      {0,-52} ║" -f $Mode)
  Write-Host "║                                                                  ║"
  Write-Host "╚══════════════════════════════════════════════════════════════════╝"
  Write-Host ""
}

# ---------------------------------------------------------------------------
# Configuration
# ---------------------------------------------------------------------------
$ProjectName = "{{PROJECT_NAME}}"
$TaskFlow = "{{TASK_FLOW}}"

# ---------------------------------------------------------------------------
# Fab CLI Wrappers (verified against fab v0.1.10)
# ---------------------------------------------------------------------------

function Test-FabAuth {
  # fab auth status outputs text; "Not logged in" means unauthenticated
  $out = & fab auth status 2>&1 | Out-String
  return ($out -notmatch "Not logged in")
}

function Get-FabTenantId {
  # Parse "  - Tenant ID: <guid>" from fab auth status text
  $out = & fab auth status 2>&1 | Out-String
  if ($out -match "Tenant ID:\s*(\S+)") { return $Matches[1] }
  return "(unavailable)"
}

function Test-FabExists {
  # fab exists outputs "* true" or "* false" (exit code always 0)
  param([string]$Path)
  $out = & fab exists $Path 2>&1 | Out-String
  return ($out -match "\* true")
}

function Get-FabProperty {
  # fab get <path> -q <jmespath> — use -q . for full JSON
  param([string]$Path, [string]$Query = ".")
  $out = & fab get $Path -q $Query 2>&1 | Out-String
  return $out.Trim()
}

function New-FabItem {
  # Create item with idempotency (Test-FabExists first) and retry
  # After creation, sets description via fab set -q description -f
  param(
    [string]$Path,
    [string]$Label,
    [string]$TreeChar = "├──",
    [string[]]$Params = @(),
    [string]$Description = "",
    [int]$MaxRetries = 3
  )

  if (Test-FabExists -Path $Path) {
    Write-Host "  $TreeChar ✅ $Label (already exists)"
    $script:DeployResults += @{ Label = $Label; Status = "exists" }
    return
  }

  $cmdArgs = @("mkdir", $Path)
  if ($Params.Count -gt 0) {
    $cmdArgs += "-P"
    $cmdArgs += ($Params -join ",")
  }

  for ($attempt = 1; $attempt -le $MaxRetries; $attempt++) {
    $errOutput = & fab @cmdArgs 2>&1 | Out-String
    if ($LASTEXITCODE -eq 0) {
      Write-Host "  $TreeChar ✅ $Label"
      $script:DeployResults += @{ Label = $Label; Status = "created" }
      # Set description if provided (fire-and-forget, non-fatal)
      if ($Description) {
        & fab set $Path -q description -i $Description -f 2>&1 | Out-Null
      }
      return
    }
    if ($attempt -lt $MaxRetries) {
      $wait = $attempt * 10
      Write-Host "  $TreeChar ⚠️  $Label (attempt $attempt failed, retrying in ${wait}s...)"
      Write-Host "         Error: $($errOutput.Trim())"
      Start-Sleep -Seconds $wait
    }
  }

  Write-Host "  $TreeChar ❌ $Label (failed after $MaxRetries attempts)"
  Write-Host "         Error: $($errOutput.Trim())"
  $script:DeployResults += @{ Label = $Label; Status = "failed" }
  throw "Deployment failed: $Label"
}

function Set-FabCapacity {
  # fab assign .capacities/<name>.Capacity -W <ws>.Workspace
  # Uses capacity display NAME, not GUID. List with: fab ls .capacities
  param([string]$CapacityName, [string]$WorkspacePath)

  Write-Host "  ── Assigning capacity: $CapacityName"
  $out = & fab assign ".capacities/$CapacityName.Capacity" -W $WorkspacePath 2>&1 | Out-String
  if ($LASTEXITCODE -eq 0) {
    Write-Host "  ── ✅ Capacity assigned"
  } else {
    Write-Host "  ── ⚠️  Could not assign capacity '$CapacityName'"
    Write-Host "         Run 'fab ls .capacities' to see available names"
    Write-Host "         Error: $($out.Trim())"
  }
}

function Select-FabCapacity {
  <#
  .SYNOPSIS Interactive capacity picker. Lists available capacities and lets
  the user select by number. Supports env var override (FABRIC_CAPACITY_NAME).
  Returns the selected capacity name (without .Capacity suffix), or empty string if skipped.
  #>

  # Check env var first
  $envVal = [System.Environment]::GetEnvironmentVariable("FABRIC_CAPACITY_NAME")
  if ($envVal) {
    Write-Host "  ── Using capacity from env: $envVal"
    return $envVal
  }

  Write-Host "  Fetching available capacities..."
  $raw = & fab ls .capacities 2>&1 | Out-String
  $lines = $raw -split "`n" | ForEach-Object { $_.Trim() } | Where-Object { $_ -ne "" -and $_ -match "\.Capacity$" }

  if ($lines.Count -eq 0) {
    Write-Host "  ── ⚠️  No capacities found (check permissions or tenant)"
    return ""
  }

  # Strip .Capacity suffix for display
  $names = $lines | ForEach-Object { $_ -replace "\.Capacity$", "" }

  Write-Host ""
  Write-Host "  Available capacities:"
  Write-Host "  ─────────────────────"
  for ($i = 0; $i -lt $names.Count; $i++) {
    Write-Host ("  {0,3})  {1}" -f ($i + 1), $names[$i])
  }
  Write-Host ("  {0,3})  {1}" -f 0, "[Skip — no capacity assignment]")
  Write-Host ""

  do {
    $input = Read-Host "  ? Select capacity (enter number)"
    $num = 0
    $valid = [int]::TryParse($input, [ref]$num)
  } while (-not $valid -or $num -lt 0 -or $num -gt $names.Count)

  if ($num -eq 0) {
    Write-Host "  ── Skipping capacity assignment"
    return ""
  }

  $selected = $names[$num - 1]
  Write-Host "  ── Selected: $selected"
  return $selected
}

function Add-ManualStep {
  # Only .Dashboard truly lacks fab mkdir. All other items support CLI creation.
  param([string]$Label, [string]$TreeChar = "├──")
  Write-Host "  $TreeChar ⏭️  [MANUAL] $Label"
  $script:DeployResults += @{ Label = $Label; Status = "manual" }
}

# ---------------------------------------------------------------------------
# Interactive prompts (with env var fallbacks)
# ---------------------------------------------------------------------------
function Prompt-Value {
  param(
    [string]$EnvVarName,
    [string]$PromptText,
    [string]$DefaultValue = "",
    [switch]$Optional
  )

  $envValue = [System.Environment]::GetEnvironmentVariable($EnvVarName)
  if ($envValue) { return $envValue }

  if ($DefaultValue) {
    $input = Read-Host "  ? $PromptText (Enter = $DefaultValue, or type to rename)"
    if ([string]::IsNullOrWhiteSpace($input)) { return $DefaultValue }
    return $input
  } elseif ($Optional) {
    $input = Read-Host "  ? $PromptText (optional, Enter to skip)"
    if ([string]::IsNullOrWhiteSpace($input)) { return "" }
    return $input
  } else {
    return Read-Host "  ? $PromptText"
  }
}

# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------
function Main {
  Print-Banner -ProjectName $ProjectName -TaskFlow $TaskFlow -Mode "Deploy to Fabric"

  # Preflight
  Write-Host "  Checking prerequisites..."
  $fabCmd = Get-Command fab -ErrorAction SilentlyContinue
  if (-not $fabCmd) {
    Write-Host "  ❌ Fabric CLI (fab) not found. Install: pip install ms-fabric-cli"
    return
  }
  Write-Host "  ── ✅ Fabric CLI found ($(fab --version 2>&1 | Select-Object -First 1))"
  Write-Host ""

  $script:DeployResults = @()

  # ---------------------------------------------------------------------------
  # Configuration
  # ---------------------------------------------------------------------------
  Write-Host "┌──────────────────────────────────────────────────────────────────┐"
  Write-Host "│  CONFIGURATION                                                   │"
  Write-Host "│  Fill in the values below or set as environment variables.       │"
  Write-Host "└──────────────────────────────────────────────────────────────────┘"
  Write-Host ""

  $WorkspaceName = Prompt-Value -EnvVarName "FABRIC_WORKSPACE_NAME" -PromptText "Workspace name" -DefaultValue "{{PROJECT_SLUG}}-dev"
  $CapacityName = Select-FabCapacity

  # {{TASK_FLOW_SPECIFIC_PROMPTS}}

  Write-Host ""
  Write-Host "┌──────────────────────────────────────────────────────────────────┐"
  Write-Host "│  DEPLOYMENT PLAN                                                 │"
  Write-Host ("│{0,-66}│" -f "  Task flow: $TaskFlow  |  Items: {{ITEM_COUNT}}  |  Waves: {{WAVE_COUNT}}")
  Write-Host "└──────────────────────────────────────────────────────────────────┘"
  Write-Host ""

  # {{DEPLOYMENT_PLAN_PREVIEW}}

  Write-Host ""
  $confirm = Read-Host "  ? Proceed with deployment? [Y/n]"
  if ($confirm -and $confirm -notmatch "^[Yy]") {
    Write-Host "  Deployment cancelled."
    return
  }

  # ---------------------------------------------------------------------------
  # Authenticate
  # ---------------------------------------------------------------------------
  Write-Host ""
  Write-Host "  Checking authentication..."
  if (-not (Test-FabAuth)) {
    Write-Host "  ── Not authenticated — launching browser login..."
    & fab auth login 2>$null
    if (-not (Test-FabAuth)) {
      Write-Host "  ── ❌ Authentication failed. Run: fab auth login"
      return
    }
  }
  Write-Host "  ── ✅ Authenticated"

  # ---------------------------------------------------------------------------
  # Workspace (requires capacity for creation; uses fab assign for existing)
  # ---------------------------------------------------------------------------
  Write-Host ""
  $wsPath = "$WorkspaceName.Workspace"
  if (Test-FabExists -Path $wsPath) {
    Write-Host "  ── ✅ Workspace already exists: $WorkspaceName"
    # Optionally reassign capacity on existing workspace
    if ($CapacityName) {
      Set-FabCapacity -CapacityName $CapacityName -WorkspacePath $wsPath
    }
  } else {
    # New workspace — use fab config set default_capacity (handles special chars in names)
    if (-not $CapacityName) {
      Write-Host "  ── ❌ Cannot create workspace without a capacity."
      Write-Host "         Select a capacity above, or set FABRIC_CAPACITY_NAME env var."
      Write-Host "         Alternatively, set a default: fab config set default_capacity <name>"
      return
    }
    Write-Host "  Setting default capacity: $CapacityName"
    & fab config set default_capacity $CapacityName 2>&1 | Out-Null
    Write-Host "  Creating workspace..."
    New-FabItem -Path $wsPath -Label "Workspace: $WorkspaceName" -TreeChar "──"
  }

  # ---------------------------------------------------------------------------
  # Wave Deployment
  # ---------------------------------------------------------------------------
  # {{WAVE_DEPLOYMENT}}
  # Agent: Insert New-FabItem calls grouped by wave, e.g.:
  #
  #   Write-Host "`n  Wave 1 — Foundation"
  #   New-FabItem -Path "$wsPath/bronze-lh.Lakehouse" -Label "Lakehouse: bronze-lh" -Params @("enableSchemas=true") -Description "Bronze layer raw data store"
  #   New-FabItem -Path "$wsPath/my-env.Environment" -Label "Environment: my-env" -TreeChar "└──" -Description "Spark/Python runtime"
  #
  # -Description sets fab set -q description after creation (from architecture handoff purpose field)
  # Naming: use underscores for Eventstream, MLExperiment, MLModel (hyphens rejected)
  #
  # Items that support fab mkdir (verified via fab desc):
  #   .Lakehouse, .Warehouse, .Eventhouse, .KQLDatabase, .SQLDatabase,
  #   .Notebook, .Environment, .DataPipeline, .Eventstream, .CopyJob,
  #   .SparkJobDefinition, .MLExperiment, .MLModel, .KQLQueryset,
  #   .SemanticModel, .Report, .Reflex, .KQLDashboard, .GraphQLApi
  #
  # Portal-only (no fab mkdir):
  #   .Dashboard — use Add-ManualStep

  # ---------------------------------------------------------------------------
  # Deployment Summary
  # ---------------------------------------------------------------------------
  Write-Host ""
  Write-Host "┌──────────────────────────────────────────────────────────────────┐"
  Write-Host "│  DEPLOYMENT SUMMARY                                              │"
  Write-Host "└──────────────────────────────────────────────────────────────────┘"
  Write-Host ""
  $created = @($script:DeployResults | Where-Object { $_.Status -eq "created" }).Count
  $existed = @($script:DeployResults | Where-Object { $_.Status -eq "exists" }).Count
  $failed  = @($script:DeployResults | Where-Object { $_.Status -eq "failed" }).Count
  $manual  = @($script:DeployResults | Where-Object { $_.Status -eq "manual" }).Count
  foreach ($r in $script:DeployResults) {
    $icon = switch ($r.Status) {
      "created" { "✅ Created" }
      "exists"  { "✅ Exists " }
      "failed"  { "❌ Failed " }
      "manual"  { "⏭️  Manual " }
      default   { "?  Unknown" }
    }
    Write-Host "  $icon  $($r.Label)"
  }
  Write-Host ""
  Write-Host "  Created: $created  |  Exists: $existed  |  Failed: $failed  |  Manual: $manual"

  # ---------------------------------------------------------------------------
  # Post-Deployment Metadata
  # ---------------------------------------------------------------------------
  Write-Host ""
  Write-Host "┌──────────────────────────────────────────────────────────────────┐"
  Write-Host "│  POST-DEPLOYMENT METADATA                                       │"
  Write-Host "└──────────────────────────────────────────────────────────────────┘"
  Write-Host ""

  $wsJson = Get-FabProperty -Path $wsPath
  try {
    $wsInfo = $wsJson | ConvertFrom-Json
    $WorkspaceId = $wsInfo.id
  } catch {
    $WorkspaceId = "(unavailable)"
  }
  Write-Host "  Workspace ID:   $WorkspaceId"
  Write-Host "  Tenant ID:      $(Get-FabTenantId)"
  Write-Host "  Workspace URL:  https://app.fabric.microsoft.com/groups/$WorkspaceId"
  Write-Host ""

  Write-Host "  Items in workspace:"
  & fab ls $wsPath -l 2>&1 | ForEach-Object { Write-Host "    $_" }
  Write-Host ""
  Write-Host "  ℹ️  Run 'fab get $wsPath/<item>.<Type> -q .' to inspect any item"
}

Main
